/**
 * Bootstrap a local devnet + indexer + privacy pool + ForgeYields mock + anonymizer,
 * then generate `demo/.env.local` so `npm run dev` in `demo/` connects to this stack.
 *
 * Stays alive until SIGINT (Ctrl+C). The devnet is in-memory only — kill the process
 * and everything goes away.
 *
 * Usage:
 *   cd e2e
 *   PATH=$HOME/.local/bin:$PATH npx tsx scripts/bootstrap-demo.ts
 *
 * Then in another terminal:
 *   cd demo && npm run dev
 */
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { Devnet } from "@starkware-libs/starknet-privacy-sdk/testing";
import { createE2eTestEnv } from "../src/harness.js";
import { deployTestTokens } from "../src/vesu-setup.js";
import { deployForgeInfra } from "../src/forge-setup.js";
import { u256Calldata } from "../src/utils.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "../..");

console.log("\n=== Bootstrapping local devnet for Forge demo UI ===\n");

const devnet = new Devnet();
const env = await createE2eTestEnv(devnet, {
  indexer: { logFile: "bootstrap-demo-indexer.log" },
});

const { admin, provider, alice, bob, privacy } = env.env;

console.log("Devnet + indexer + privacy pool ready.");
console.log(`  RPC:     ${devnet.url}`);
console.log(`  Indexer: ${env.indexer.apiUrl}`);
console.log(`  Pool:    ${privacy.address}`);

// Deploy test tokens (USDC + BTC) — reuses vesu-setup helper, gives us a working USD token.
console.log("\nDeploying test tokens (USD, BTC)…");
const tokens = await deployTestTokens(admin, provider);
console.log(`  USD: ${tokens.usdToken}`);

// Deploy Forge mock gateway + anonymizer.
console.log("\nDeploying Forge mock gateway + anonymizer…");
const forge = await deployForgeInfra(admin, provider, {
  name: "Forge USDC Strategy",
  symbol: "fyUSDC",
  underlying: tokens.usdToken,
  salt: "0x900",
});
console.log(`  Anonymizer: ${forge.anonymizer}`);
console.log(`  Gateway:    ${forge.gateway}`);

// Mint a healthy amount of USD to alice and bob so they can play in the UI.
const ONE_TOKEN = 10n ** 18n;
const mintAmount = 1_000n * ONE_TOKEN;
console.log(`\nMinting ${mintAmount / ONE_TOKEN} USD to alice and bob…`);
for (const account of [alice, bob]) {
  const tx = await admin.execute({
    contractAddress: tokens.usdToken,
    entrypoint: "mint",
    calldata: [account.address, ...u256Calldata(mintAmount)],
  });
  await provider.waitForTransaction(tx.transaction_hash);
}

// Fetch the predeployed account private keys from devnet so we can wire them into the demo.
const predeployedResponse = await fetch(devnet.url, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    jsonrpc: "2.0",
    id: 1,
    method: "devnet_getPredeployedAccounts",
  }),
});
const predeployed = (
  (await predeployedResponse.json()) as {
    result: { address: string; private_key: string; public_key: string }[];
  }
).result;

// Match accounts by address. With seed=42 + userAccounts=2: [alice, bob, admin].
const findKey = (address: string): string => {
  const norm = (s: string) => BigInt(s).toString(16);
  const match = predeployed.find((p) => norm(p.address) === norm(address));
  if (!match) throw new Error(`No private key found for ${address}`);
  return match.private_key;
};

const accounts = [
  {
    name: "admin",
    address: admin.address,
    privateKey: findKey(admin.address),
    viewingKey: "0xADAD",
    admin: true,
  },
  {
    name: "alice",
    address: alice.address,
    privateKey: findKey(alice.address),
    viewingKey: "0xA11CE",
  },
  {
    name: "bob",
    address: bob.address,
    privateKey: findKey(bob.address),
    viewingKey: "0xB0B",
  },
];

// Build the demo .env.local
const tokensConfig = [
  { name: "USD", address: tokens.usdToken, decimals: 18, fee: true },
  { name: "BTC", address: tokens.btcToken, decimals: 18 },
];
const forgeConfig = {
  strategies: [
    { token: "USD", gateway: forge.gateway, symbol: "fyUSDC" },
  ],
};

const envLines = [
  `# Generated by bootstrap-demo.ts at ${new Date().toISOString()}`,
  `# Devnet runs in-memory; kill the bootstrap process to tear everything down.`,
  ``,
  `VITE_RPC_URL=${devnet.url}`,
  `VITE_INDEXER_URL=${env.indexer.apiUrl}`,
  `VITE_POOL_ADDRESS=${privacy.address}`,
  `VITE_POOL_CLASS_HASH=${privacy.classHash ?? "0x0"}`,
  `VITE_COMPLIANCE_PUBLIC_KEY=0x0`,
  `VITE_PROOF_VALIDITY_BLOCKS=450`,
  // SN_SEPOLIA chain id — devnet is configured via --chain-id TESTNET but the SDK's harness
  // tells the SDK to use SN_SEPOLIA constant. Keep it consistent with harness.ts:119.
  `VITE_CHAIN_ID=0x534e5f5345504f4c4941`,
  `VITE_TOKENS=${JSON.stringify(tokensConfig)}`,
  `VITE_ACCOUNTS=${JSON.stringify(accounts)}`,
  `VITE_FORGE_ANONYMIZER_ADDRESS=${forge.anonymizer}`,
  `VITE_FORGE=${JSON.stringify(forgeConfig)}`,
  `VITE_EXPLORER_URL=`,
  ``,
];

const envPath = join(repoRoot, "demo", ".env.local");
writeFileSync(envPath, envLines.join("\n"));

console.log(`\nWrote ${envPath}`);
console.log("\n========================================================");
console.log("READY. In another terminal:");
console.log("   cd demo && npm run dev");
console.log("Then open http://localhost:5173/");
console.log("Press Ctrl+C in THIS terminal to tear everything down.");
console.log("========================================================\n");

// Keep alive forever — kill via SIGINT.
process.on("SIGINT", async () => {
  console.log("\nShutting down…");
  await env.indexer.shutdown();
  await devnet.cleanup();
  process.exit(0);
});

// Park forever
await new Promise(() => {});
