/**
 * Deploy ForgeYields mock gateway + anonymizer to a live StarkNet network.
 *
 * Deploys the test USD token (unless already set in env), MockForgeYieldsGateway
 * for the USD strategy, and ForgeYieldsAnonymizer. All output addresses are
 * written to `.env.deployed`.
 *
 * Prerequisites:
 *   cd e2e/contracts/test-token && scarb build
 *   cd e2e/contracts/forge      && scarb build
 *   scarb build                                # ForgeYieldsAnonymizer (repo root)
 *
 * Usage: npm run deploy-forge (from e2e/, with .env populated)
 *
 * Set `DEPLOY_SALT_SEED` to deploy fresh instances at new addresses (mixed into
 * every per-call salt via `deployContract`).
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { setupAdmin } from "../src/utils.js";
import { deployTestTokens } from "../src/vesu-setup.js";
import { deployForgeInfra } from "../src/forge-setup.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const { adminAccount, provider } = setupAdmin();

// Reuse existing tokens if provided, otherwise deploy fresh ones
const existingUsd = process.env.USD_TOKEN_ADDRESS;
const existingBtc = process.env.BTC_TOKEN_ADDRESS;
const hasExistingTokens =
  existingUsd && existingUsd !== "0x0" && existingBtc && existingBtc !== "0x0";

let usdToken: string;
let btcToken: string;
if (hasExistingTokens) {
  usdToken = existingUsd;
  btcToken = existingBtc;
  console.log(`\nReusing existing tokens:`);
  console.log(`  USD: ${usdToken}`);
  console.log(`  BTC: ${btcToken}`);
} else {
  console.log("\n=== Deploying test tokens ===");
  ({ usdToken, btcToken } = await deployTestTokens(adminAccount, provider));
}

console.log(
  "\n=== Deploying Forge USDC strategy (mock gateway + anonymizer) ===",
);
const forge = await deployForgeInfra(adminAccount, provider, {
  name: "Forge USDC Strategy",
  symbol: "fyUSDC",
  underlying: usdToken,
  salt: "0x900",
});

// Demo app config — single-strategy listing on the USD pair.
const forgeConfig = {
  strategies: [{ token: "USD", gateway: forge.gateway, symbol: "fyUSDC" }],
};

const envVars: Record<string, string> = {
  USD_TOKEN_ADDRESS: usdToken,
  BTC_TOKEN_ADDRESS: btcToken,
  FORGE_GATEWAY_ADDRESS: forge.gateway,
  FORGE_ANONYMIZER_ADDRESS: forge.anonymizer,
  VITE_FORGE_ANONYMIZER_ADDRESS: forge.anonymizer,
  VITE_FORGE: JSON.stringify(forgeConfig),
};

const outputPath = join(__dirname, "../.env.deployed");
const header = `# Generated by deploy-forge.ts at ${new Date().toISOString()}\n`;
const body = Object.entries(envVars)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
writeFileSync(outputPath, header + body + "\n");

console.log(`\nDeployment output written to ${outputPath}`);
console.log("\nEnvironment variables:");
for (const [key, value] of Object.entries(envVars)) {
  console.log(`  ${key}=${value}`);
}
