/**
 * Deploy the NEAR Intents anonymizer (and its lazy-deploy MailboxReceiver
 * class) to a live Starknet network — Sepolia or mainnet.
 *
 * Prerequisites:
 *   scarb build -p near_intents_anonymizer    # from repo root
 *
 * Required env:
 *   PRIVACY_CONTRACT_ADDRESS  — address of the deployed privacy pool
 *                              (must be a build that includes the
 *                              `unfilled-open-note-support` features:
 *                              the `depositor` field on `Note` and the
 *                              public `deposit_to_open_note` entrypoint).
 *   STARKNET_RPC, ADMIN_ADDRESS, ADMIN_PRIVATE_KEY  — see e2e/.env.example
 *
 * Optional env:
 *   DEPLOY_SALT_SEED          — bump to deploy a fresh instance at a
 *                              new address.
 *
 * Usage:
 *   cd e2e && npm run deploy-near-intents-anonymizer
 *
 * Output:
 *   Appends class hashes + addresses to `e2e/.env.deployed`. Hand these
 *   to the SDK dev so they can hardcode the anonymizer address and
 *   receiver class hash for mailbox-address derivation.
 */

import { appendFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { setupAdmin } from "../src/utils.js";
import { deployNearIntentsAnonymizer } from "../src/near-intents-anonymizer-setup.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const privacyAddress = process.env.PRIVACY_CONTRACT_ADDRESS;
if (!privacyAddress || privacyAddress === "0x0") {
  throw new Error(
    "PRIVACY_CONTRACT_ADDRESS not set — point at the privacy pool deployment first.",
  );
}

const { adminAccount, provider } = setupAdmin();

const deployment = await deployNearIntentsAnonymizer(
  adminAccount,
  provider,
  privacyAddress,
);

const envVars: Record<string, string> = {
  NEAR_INTENTS_ANONYMIZER_ADDRESS: deployment.anonymizerAddress,
  NEAR_INTENTS_ANONYMIZER_CLASS_HASH: deployment.anonymizerClassHash,
  NEAR_INTENTS_RECEIVER_CLASS_HASH: deployment.receiverClassHash,
  // SDK side
  VITE_NEAR_INTENTS_ANONYMIZER_ADDRESS: deployment.anonymizerAddress,
  VITE_NEAR_INTENTS_RECEIVER_CLASS_HASH: deployment.receiverClassHash,
};

const outputPath = join(__dirname, "../.env.deployed");
const header = `\n# Generated by deploy-near-intents-anonymizer.ts at ${new Date().toISOString()}\n`;
const body = Object.entries(envVars)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
appendFileSync(outputPath, header + body + "\n");

console.log(`\nDeployment output appended to ${outputPath}`);
console.log("\nEnvironment variables:");
for (const [key, value] of Object.entries(envVars)) {
  console.log(`  ${key}=${value}`);
}
