/**
 * Deploy Ekubo infrastructure to a live StarkNet network (e.g. Sepolia).
 *
 * Deploys test tokens (unless already set in env), Ekubo Core + Router +
 * Positions with a seeded pool, and the EkuboSwapAnonymizer executor.
 * All output addresses are written to `ekubo-deployment.env`.
 *
 * Prerequisites:
 *   cd e2e/contracts/ekubo      && scarb build   # Ekubo Core/Router/Positions
 *   cd e2e/contracts/test-token && scarb build   # TestToken
 *   scarb build                              # EkuboSwapAnonymizer (repo root)
 *
 * Usage: npm run deploy-ekubo (from e2e/, with .env populated)
 */

import { appendFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { setupAdmin, requireEnv } from "../src/utils.js";
import {
  deployEkuboInfra,
  deployEkuboExecutor,
  DEVNET_POOL_CONFIG,
  type EkuboPoolConfig,
} from "../src/ekubo-setup.js";
import { deployTestTokens } from "../src/vesu-setup.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const { adminAccount, provider } = setupAdmin();

// Reuse existing tokens if provided, otherwise deploy fresh ones
const existingUsd = process.env.USD_TOKEN_ADDRESS;
const existingBtc = process.env.BTC_TOKEN_ADDRESS;
const hasExistingTokens =
  existingUsd && existingUsd !== "0x0" && existingBtc && existingBtc !== "0x0";

let usdToken: string;
let btcToken: string;
if (hasExistingTokens) {
  usdToken = existingUsd;
  btcToken = existingBtc;
  console.log(`\nReusing existing tokens:`);
  console.log(`  USD: ${usdToken}`);
  console.log(`  BTC: ${btcToken}`);
} else {
  console.log("\n=== Deploying test tokens ===");
  ({ usdToken, btcToken } = await deployTestTokens(adminAccount, provider));
}

// Pool config: use env overrides where set, fall back to DEVNET_POOL_CONFIG
const poolConfig: EkuboPoolConfig = {
  fee: process.env.EKUBO_POOL_FEE
    ? BigInt(process.env.EKUBO_POOL_FEE)
    : DEVNET_POOL_CONFIG.fee,
  tickSpacing: process.env.EKUBO_TICK_SPACING
    ? BigInt(process.env.EKUBO_TICK_SPACING)
    : DEVNET_POOL_CONFIG.tickSpacing,
  extension: process.env.EKUBO_EXTENSION ?? DEVNET_POOL_CONFIG.extension,
  initialTick: process.env.EKUBO_POOL_INITIAL_TICK
    ? BigInt(process.env.EKUBO_POOL_INITIAL_TICK)
    : DEVNET_POOL_CONFIG.initialTick,
  seedAmount0: process.env.EKUBO_SEED_AMOUNT0
    ? BigInt(process.env.EKUBO_SEED_AMOUNT0)
    : DEVNET_POOL_CONFIG.seedAmount0,
  seedAmount1: process.env.EKUBO_SEED_AMOUNT1
    ? BigInt(process.env.EKUBO_SEED_AMOUNT1)
    : DEVNET_POOL_CONFIG.seedAmount1,
  positionLowerBound: process.env.EKUBO_POSITION_LOWER_BOUND
    ? BigInt(process.env.EKUBO_POSITION_LOWER_BOUND)
    : DEVNET_POOL_CONFIG.positionLowerBound,
  positionUpperBound: process.env.EKUBO_POSITION_UPPER_BOUND
    ? BigInt(process.env.EKUBO_POSITION_UPPER_BOUND)
    : DEVNET_POOL_CONFIG.positionUpperBound,
  skipAhead: process.env.EKUBO_SKIP_AHEAD
    ? BigInt(process.env.EKUBO_SKIP_AHEAD)
    : DEVNET_POOL_CONFIG.skipAhead,
};

console.log("\n=== Deploying Ekubo infrastructure ===");
const ekubo = await deployEkuboInfra(
  adminAccount,
  provider,
  { usdToken, btcToken },
  poolConfig,
);

console.log("\n=== Deploying Ekubo executor ===");
const executorAddress = await deployEkuboExecutor(
  adminAccount,
  provider,
  requireEnv("VITE_POOL_ADDRESS"),
);

const ekuboPool = {
  token0: ekubo.poolToken0,
  token1: ekubo.poolToken1,
  fee: poolConfig.fee.toString(),
  tickSpacing: poolConfig.tickSpacing.toString(),
  extension: poolConfig.extension,
  skipAhead: poolConfig.skipAhead.toString(),
};

// Build output env vars
const envVars: Record<string, string> = {
  // Ekubo addresses (used by e2e scripts)
  EKUBO_CORE_ADDRESS: ekubo.coreAddress,
  EKUBO_ROUTER_ADDRESS: ekubo.routerAddress,
  EKUBO_POSITIONS_ADDRESS: ekubo.positionsAddress,
  EKUBO_POOL_TOKEN0: ekubo.poolToken0,
  EKUBO_POOL_TOKEN1: ekubo.poolToken1,
  EKUBO_POOL_FEE: poolConfig.fee.toString(),
  EKUBO_TICK_SPACING: poolConfig.tickSpacing.toString(),
  EKUBO_EXTENSION: poolConfig.extension,
  EKUBO_SKIP_AHEAD: poolConfig.skipAhead.toString(),
  EXECUTOR_ADDRESS: executorAddress,
  // Demo app format
  VITE_EKUBO_EXECUTOR_ADDRESS: executorAddress,
  VITE_EKUBO_CORE_ADDRESS: ekubo.coreAddress,
  VITE_EKUBO_ROUTER_ADDRESS: ekubo.routerAddress,
  VITE_EKUBO_POOL: JSON.stringify(ekuboPool),
};

// Write to file
const outputPath = join(__dirname, "../.env.deployed");
const header = `\n# Generated by deploy-ekubo.ts at ${new Date().toISOString()}\n`;
const body = Object.entries(envVars)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
appendFileSync(outputPath, header + body + "\n");

console.log(`\nDeployment output written to ${outputPath}`);
console.log("\nEnvironment variables:");
for (const [key, value] of Object.entries(envVars)) {
  console.log(`  ${key}=${value}`);
}
