/**
 * Deploy Vesu lending infrastructure to a live StarkNet network (e.g. Sepolia).
 *
 * Deploys test tokens (unless already set in env), Vesu PoolFactory + mock
 * oracles + Oracle + Pool with USD/BTC pairs, seeds liquidity, and deploys
 * VesuLendingAnonymizer. All output addresses are written to `vesu-deployment.env`.
 *
 * Prerequisites:
 *   cd e2e/contracts/test-token && scarb build   # TestToken
 *   cd e2e/contracts/vesu      && scarb build   # Vesu Pool, Oracle, etc.
 *   scarb build                             # VesuLendingAnonymizer (repo root)
 *
 * Usage: npm run deploy-vesu (from e2e/, with .env populated)
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { setupAdmin } from "../src/utils.js";
import {
  deployTestTokens,
  deployVesuInfra,
  deployVesuAnonymizer,
} from "../src/vesu-setup.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const { adminAccount, provider } = setupAdmin();

// Reuse existing tokens if provided, otherwise deploy fresh ones
const existingUsd = process.env.USD_TOKEN_ADDRESS;
const existingBtc = process.env.BTC_TOKEN_ADDRESS;
const hasExistingTokens =
  existingUsd && existingUsd !== "0x0" && existingBtc && existingBtc !== "0x0";

let usdToken: string;
let btcToken: string;
if (hasExistingTokens) {
  usdToken = existingUsd;
  btcToken = existingBtc;
  console.log(`\nReusing existing tokens:`);
  console.log(`  USD: ${usdToken}`);
  console.log(`  BTC: ${btcToken}`);
} else {
  console.log("\n=== Deploying test tokens ===");
  ({ usdToken, btcToken } = await deployTestTokens(adminAccount, provider));
}

console.log("\n=== Deploying Vesu infrastructure ===");
const vesu = await deployVesuInfra(adminAccount, provider, {
  usdToken,
  btcToken,
});

console.log("\n=== Deploying Vesu lending anonymizer ===");
const anonymizerAddress = await deployVesuAnonymizer(adminAccount, provider);

// Build output env vars
const tokens = [
  { name: "USD", address: usdToken, decimals: 18 },
  { name: "BTC", address: btcToken, decimals: 18 },
];

const vesuConfig = {
  vaults: [
    { token: "USD", vTokenAddress: vesu.usdVToken },
    { token: "BTC", vTokenAddress: vesu.btcVToken },
  ],
};

const envVars: Record<string, string> = {
  // Token addresses (used by e2e scripts and deploy-ekubo)
  USD_TOKEN_ADDRESS: usdToken,
  BTC_TOKEN_ADDRESS: btcToken,
  // Vesu addresses (used by e2e scripts)
  VESU_POOL_FACTORY_ADDRESS: vesu.factoryAddress,
  VESU_POOL_ADDRESS: vesu.poolAddress,
  VESU_ORACLE_ADDRESS: vesu.oracleAddress,
  USD_VTOKEN_ADDRESS: vesu.usdVToken,
  BTC_VTOKEN_ADDRESS: vesu.btcVToken,
  VESU_LENDING_ANONYMIZER_ADDRESS: anonymizerAddress,
  // Demo app format
  VITE_TOKENS: JSON.stringify(tokens),
  VITE_VESU_LENDING_ANONYMIZER_ADDRESS: anonymizerAddress,
  VITE_VESU: JSON.stringify(vesuConfig),
};

// Write to file
const outputPath = join(__dirname, "../.env.deployed");
const header = `# Generated by deploy-vesu.ts at ${new Date().toISOString()}\n`;
const body = Object.entries(envVars)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
writeFileSync(outputPath, header + body + "\n");

console.log(`\nDeployment output written to ${outputPath}`);
console.log("\nEnvironment variables:");
for (const [key, value] of Object.entries(envVars)) {
  console.log(`  ${key}=${value}`);
}
