[workspace]
members = [
    "packages/privacy",
]


[workspace.package]
version = "0.1.0"
edition = "2024_07"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.17.0-rc.1"
snforge_std = { version = "0.55.0+nightly-2026-02-20", registry = "https://scarbs.dev/" }
assert_macros = "2.17.0-rc.1"
openzeppelin = { git = "https://github.com/noa-starkware/cairo-contracts", rev = "d5f9f389c5c6fc91fe58eff8fc7ab83e5a100e05"}
starkware_utils = { git ="https://github.com/starkware-libs/starkware-starknet-utils", rev="0ccab71bd2b1809a3db1823dd482e2a1ed65812e" }
starkware_utils_testing = { git="https://github.com/starkware-libs/starkware-starknet-utils", rev="0ccab71bd2b1809a3db1823dd482e2a1ed65812e" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[[target.starknet-contract]]
casm = true

[[test]]
name = "unittest"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[profile.release.cairo]
inlining-strategy = 250