[workspace]
members = [
    "packages/ekubo_swap_anonymizer",
    "packages/privacy",
    "packages/sub_account_anonymizer",
    "packages/vesu_lending_anonymizer",
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.17.0"
snforge_std = "0.59.0"
assert_macros = "2.17.0"
openzeppelin = "3.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/starknet-contracts", rev = "8b4de8b5701d10b101c06b786740bf45b6cf15cb" }
starkware_utils = { git ="https://github.com/starkware-libs/starkware-starknet-utils", rev="671bac4dd7ec765ffb2e64711f93acef94802d43" }
starkware_utils_testing = { git="https://github.com/starkware-libs/starkware-starknet-utils", rev="671bac4dd7ec765ffb2e64711f93acef94802d43" }
starkware_accounts = { git="https://github.com/starkware-libs/starkware-starknet-utils", rev="671bac4dd7ec765ffb2e64711f93acef94802d43" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[[target.starknet-contract]]
casm = true

[[test]]
name = "unittest"

[profile.release.cairo]
inlining-strategy = 250
