[package]
name = "privacy"
readme = "README.md"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
starkware_utils.workspace = true

[dev-dependencies]
assert_macros.workspace = true
ekubo.workspace = true
ekubo_swap_anonymizer = { path = "../ekubo_swap_anonymizer", features = ["test_utils"] }
snforge_std.workspace = true
starkware_accounts.workspace = true
starkware_utils_testing.workspace = true
sub_account_anonymizer = { path = "../sub_account_anonymizer", features = ["test_utils"] }
vesu_lending_anonymizer = { path = "../vesu_lending_anonymizer", features = ["test_utils"] }

[[test]]
name = "privacy_unittest"
build-external-contracts = [
    "starkware_utils::erc20::erc20_mocks::DualCaseERC20Mock",
    "starkware_accounts::sub_account::SubAccount",
    "ekubo_swap_anonymizer::ekubo_swap_anonymizer::EkuboSwapAnonymizer",
    "ekubo_swap_anonymizer::test_utils_contracts::mock_ekubo_amm::MockEkuboAMM",
    "sub_account_anonymizer::sub_account_anonymizer::SubAccountAnonymizer",
    "sub_account_anonymizer::test_utils_contracts::mock_dapp::MockDapp",
    "vesu_lending_anonymizer::vesu_lending_anonymizer::VesuLendingAnonymizer",
    "vesu_lending_anonymizer::test_utils_contracts::mock_vesu_vault::MockVesuVault",
    "vesu_lending_anonymizer::test_utils_contracts::mock_vesu_vault::MockVesuVaultNoop",
    "vesu_lending_anonymizer::test_utils_contracts::mock_vesu_vault::MockVesuVaultOverflow",
]

[features]
test_contracts = []

[scripts]
test = "snforge test"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[profile.release.cairo]
inlining-strategy = 250