[package]
name = "test_mocks"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[lib]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
