pub(crate) const VIEWING_KEY_ALREADY_EXISTS: felt252 = 'VIEWING_KEY_ALREADY_EXISTS';
pub(crate) const ENC_VIEWING_KEY_ALREADY_EXISTS: felt252 = 'ENC_VIEWING_KEY_ALREADY_EXISTS';
pub(crate) const INVALID_VIEWING_KEY: felt252 = 'INVALID_VIEWING_KEY';
pub(crate) const INVALID_ENC_VIEWING_KEY: felt252 = 'INVALID_ENC_VIEWING_KEY';
