pub const ZERO_PRIVACY_POOL: felt252 = 'ZERO_PRIVACY_POOL';
pub const INVALID_CALLER: felt252 = 'INVALID_CALLER';
pub const ZERO_SWAP_CONTRACT: felt252 = 'ZERO_SWAP_CONTRACT';
pub const ZERO_SWAP_SELECTOR: felt252 = 'ZERO_SWAP_SELECTOR';
pub const ZERO_TOKEN: felt252 = 'ZERO_TOKEN';
pub const ZERO_AMOUNT: felt252 = 'ZERO_AMOUNT';
pub const ZERO_NOTE_ID: felt252 = 'ZERO_NOTE_ID';
pub const NOTE_NOT_FOUND: felt252 = 'NOTE_NOT_FOUND';
pub const ZERO_SWAP_CALLDATA: felt252 = 'ZERO_SWAP_CALLDATA';
pub const ZERO_OWNER_ADDR: felt252 = 'ZERO_OWNER_ADDR';

