[package]
name = "ekubo_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.1"
ekubo = { git = "https://github.com/EkuboProtocol/starknet-contracts", rev = "8b4de8b5701d10b101c06b786740bf45b6cf15cb" }
openzeppelin_token = "3.0.0"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "ekubo::core::Core",
    "ekubo::router::Router",
    "ekubo::positions::Positions",
    "ekubo::owned_nft::OwnedNFT",
]
