pub const ZERO_SWAP_CONTRACT: felt252 = 'ZERO_SWAP_CONTRACT';
pub const ZERO_SWAP_SELECTOR: felt252 = 'ZERO_SWAP_SELECTOR';
pub const ZERO_IN_TOKEN: felt252 = 'ZERO_IN_TOKEN';
pub const ZERO_OUT_TOKEN: felt252 = 'ZERO_OUT_TOKEN';
pub const ZERO_AMOUNT: felt252 = 'ZERO_AMOUNT';
pub const RECEIVED_AMOUNT_OVERFLOW: felt252 = 'RECEIVED_AMOUNT_OVERFLOW';
