// TODO: Consider merging errors between different functions.
pub const ZERO_RECIPIENT_ADDR: felt252 = 'ZERO_RECIPIENT_ADDR';
pub const ZERO_TOKEN: felt252 = 'ZERO_TOKEN';
pub const ZERO_SERVER: felt252 = 'ZERO_SERVER';
pub const ZERO_SENDER_ADDR: felt252 = 'ZERO_SENDER_ADDR';
pub const ZERO_SENDER_PRIVATE_KEY: felt252 = 'ZERO_SENDER_PRIVATE_KEY';
pub const ZERO_RANDOM: felt252 = 'ZERO_RANDOM';
pub const PRIVATE_KEY_NOT_CANONICAL: felt252 = 'PRIVATE_KEY_NOT_CANONICAL';
pub const SENDER_NOT_REGISTERED: felt252 = 'SENDER_NOT_REGISTERED';
pub const SENDER_NOT_AUTHENTICATED: felt252 = 'SENDER_NOT_AUTHENTICATED';
pub const RECIPIENT_NOT_REGISTERED: felt252 = 'RECIPIENT_NOT_REGISTERED';
pub const ZERO_OWNER_ADDR: felt252 = 'ZERO_OWNER_ADDR';
pub const ZERO_OWNER_PRIVATE_KEY: felt252 = 'ZERO_OWNER_PRIVATE_KEY';
pub const NO_NOTES_TO_USE: felt252 = 'NO_NOTES_TO_USE';
pub const NO_NOTES_TO_CREATE: felt252 = 'NO_NOTES_TO_CREATE';
pub const NOTE_SUM_MISMATCH: felt252 = 'NOTE_SUM_MISMATCH';
pub const ZERO_AMOUNT: felt252 = 'ZERO_AMOUNT';
pub const CHANNEL_NOT_FOUND: felt252 = 'CHANNEL_NOT_FOUND';
pub const NOTE_INDEX_NOT_SEQUENTIAL: felt252 = 'NOTE_INDEX_NOT_SEQUENTIAL';
pub const NOTE_NOT_FOUND: felt252 = 'NOTE_NOT_FOUND';
pub const ZERO_WITHDRAWAL_TARGET: felt252 = 'ZERO_WITHDRAWAL_TARGET';

// Server errors (added for PR 2)
pub const ZERO_ENC_CHANNEL_INFO: felt252 = 'ZERO_ENC_CHANNEL_INFO';
pub const ZERO_CHANNEL_ID: felt252 = 'ZERO_CHANNEL_ID';
pub const CHANNEL_ALREADY_EXISTS: felt252 = 'CHANNEL_ALREADY_EXISTS';
pub const ZERO_NOTE_ID: felt252 = 'ZERO_NOTE_ID';
pub const ZERO_ENC_NOTE_VALUE: felt252 = 'ZERO_ENC_NOTE_VALUE';
pub const NOTE_ALREADY_EXISTS: felt252 = 'NOTE_ALREADY_EXISTS';
pub const ZERO_NULLIFIER: felt252 = 'ZERO_NULLIFIER';
pub const NULLIFIER_ALREADY_EXISTS: felt252 = 'NULLIFIER_ALREADY_EXISTS';
pub const ZERO_PUBLIC_KEY: felt252 = 'ZERO_PUBLIC_KEY';
pub const USER_ALREADY_REGISTERED: felt252 = 'USER_ALREADY_REGISTERED';
pub const USER_NOT_REGISTERED: felt252 = 'USER_NOT_REGISTERED';
pub const ZERO_USER_ADDR: felt252 = 'ZERO_USER_ADDR';
pub const EMPTY_NULLIFIERS: felt252 = 'EMPTY_NULLIFIERS';
pub const EMPTY_NEW_NOTES: felt252 = 'EMPTY_NEW_NOTES';
