use client::objects::{NewNote, NotePath};
// Used for links in the documentation.
pub use server;
use server::objects::{EncChannelInfo, EncNote};
use starknet::ContractAddress;

// TODO: Use same naming convention for the functions. (owner/sender,
// private_key/sender_private_key, etc).
#[starknet::interface]
pub trait IClient<T> {
    /// Opens a new channel from `sender_addr` to `recipient_addr`.
    ///
    /// A channel allows a sender to transfer funds to a recipient. It is one-directional and
    /// supports a single token. Only the sender can open a channel.
    ///
    /// #### Parameters
    /// - `sender_addr` (`ContractAddress`) - The address of the sender. Must not be zero.
    /// - `sender_private_key` (`felt252`) - The sender's private key. Must not be zero and must be
    /// canonical.
    /// - `recipient_addr` (`ContractAddress`) - The address of the recipient. Must not be zero.
    /// - `token` (`ContractAddress`) - The address of the token. Must not be zero.
    /// - `random` (`felt252`) - A random value (generated by the sender). Must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The recipient's address.
    /// - ([`EncChannelInfo`](server::objects::EncChannelInfo)) - The encrypted channel information.
    /// - (`felt252`) - The channel id.
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - `sender_addr` is registered with `sender_private_key` in the server.
    /// - `sender_private_key` must be canonical (less than CURVE_ORDER / 2).
    /// - `recipient_addr` is registered in the server.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_SENDER_ADDR`](client::errors::ZERO_SENDER_ADDR): Thrown if `sender_addr` is zero.
    /// - [`ZERO_SENDER_PRIVATE_KEY`](client::errors::ZERO_SENDER_PRIVATE_KEY): Thrown if
    /// `sender_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if `recipient_addr`
    /// is zero.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_RANDOM`](client::errors::ZERO_RANDOM): Thrown if `random` is zero.
    /// - [`PRIVATE_KEY_NOT_CANONICAL`](client::errors::PRIVATE_KEY_NOT_CANONICAL): Thrown if
    /// `sender_private_key` is not canonical.
    /// - [`SENDER_NOT_REGISTERED`](client::errors::SENDER_NOT_REGISTERED): Thrown if `sender_addr`
    /// is not registered in the server.
    /// - [`SENDER_NOT_AUTHENTICATED`](client::errors::SENDER_NOT_AUTHENTICATED): Thrown if
    /// `sender_addr` is not registered with `sender_private_key` in the server.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `recipient_addr` is not registered in the server.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `sender_addr`.
    fn open_channel(
        self: @T,
        sender_addr: ContractAddress,
        sender_private_key: felt252,
        recipient_addr: ContractAddress,
        token: ContractAddress,
        random: felt252,
    ) -> (ContractAddress, EncChannelInfo, felt252);

    // TODO: Add index out of bounds error?
    /// Validates `notes_to_create` are a valid redistribution of funds from `notes_to_use`.
    ///
    /// A transfer consists of nullifying existing notes owned by `owner_addr` and creating
    /// new notes for the recipients.
    /// The owner can be one of the recipients.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The owner's address. Must not be zero.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `notes_to_use` (`Span<`[`NotePath`](client::objects::NotePath)`>`) - The notes that are
    /// consumed as part of the transfer.
    /// Must not be empty.
    /// - `notes_to_create` (`Span<`[`NewNote`](client::objects::NewNote)`>`) - The notes that are
    /// created as a result of the transfer. Must not be empty and have non-zero `recipient_addr`s,
    /// `token`s, and `amount`s.
    ///
    /// #### Returns
    /// - (`Span<felt252>`) - The nullifiers of `notes_to_use`.
    /// - (`Span<`[`EncNote`](EncNote)`>`) - An encrypted representation of `notes_to_create`.
    ///
    /// #### Preconditions
    /// - `owner_addr`, `owner_private_key` must not be zero.
    /// - `notes_to_use`, `notes_to_create` must not be empty.
    /// - `notes_to_use` use valid channel and note indexes of the owner's existing notes.
    /// - `notes_to_create` have non-zero `recipient_addr`s, `token`s, and `amount`s.
    /// - Each recipient is registered in the server.
    /// - A channel exists from `owner_addr` to each recipient of the given token.
    /// - `notes_to_create` use valid (sequential) `index`s within the channel.
    /// - `owner_private_key` matches the `owner_addr`'s public key defined as part of the channels.
    /// - The sum of the amounts of `notes_to_create` equals the sum of the amounts of
    /// `notes_to_use`.
    /// - All notes are in the same token.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](client::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`NO_NOTES_TO_USE`](client::errors::NO_NOTES_TO_USE): Thrown if `notes_to_use` is empty.
    /// - [`NO_NOTES_TO_CREATE`](client::errors::NO_NOTES_TO_CREATE): Thrown if `notes_to_create` is
    /// empty.
    /// - [`NOTE_NOT_FOUND`](client::errors::NOTE_NOT_FOUND): Thrown if a note to be used is not
    /// found.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if there's a note to
    /// be created with zero as the recipient.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if there's a note to be created with
    /// zero as the token.
    /// - [`ZERO_AMOUNT`](client::errors::ZERO_AMOUNT): Thrown if there's a note to be created with
    /// zero as the amount.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if a
    /// recipient is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](client::errors::CHANNEL_NOT_FOUND): Thrown if a channel is not found
    /// for one of the `notes_to_create`.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](client::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if a note
    /// index is not sequential for one of the `notes_to_create`.
    /// - [`NOTE_SUM_MISMATCH`](client::errors::NOTE_SUM_MISMATCH): Thrown if there's a mismatch
    /// between the spent funds and the received funds.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `owner_addr`.
    fn transfer(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        notes_to_use: Span<NotePath>,
        notes_to_create: Span<NewNote>,
    ) -> (Span<felt252>, Span<EncNote>);
}
