use client::objects::{NewNote, NotePath};
use server::objects::{EncChannelInfo, EncNote};
use starknet::ContractAddress;

// TODO: Use same naming convention for the functions. (owner/sender,
// private_key/sender_private_key, etc).
#[starknet::interface]
pub trait IClient<T> {
    /// Opens a new channel from `sender_addr` to `recipient_addr`.
    ///
    /// A channel allows a sender to transfer funds to a recipient. It is one-directional and
    /// supports a single token. Only the sender can open a channel.
    ///
    /// #### Parameters
    /// - `sender_addr` (`ContractAddress`) - The address of the sender.
    /// - `sender_private_key` (`felt252`) - The sender's private key.
    /// - `recipient_addr` (`ContractAddress`) - The address of the recipient.
    /// - `token` (`ContractAddress`) - The address of the token.
    /// - `random` (`felt252`) - A random value (generated by the sender). Must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The recipient's address.
    /// - (`EncChannelInfo`) - The encrypted channel information.
    /// - (`felt252`) - The channel id.
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - `sender_addr` is registered with `sender_private_key` in the server.
    /// - `recipient_addr` is registered in the server.
    /// - A channel does not already exist from `sender_addr` to `recipient_addr` of `token`. (This
    /// will be checked by the server.)
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_SENDER_ADDR`](client::errors::ZERO_SENDER_ADDR):
    /// Thrown if `sender_addr` is zero.
    /// - [`ZERO_SENDER_PRIVATE_KEY`](client::errors::ZERO_SENDER_PRIVATE_KEY):
    /// Thrown if `sender_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR):
    /// Thrown if `recipient_addr` is zero.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_RANDOM`](client::errors::ZERO_RANDOM): Thrown if `random` is zero.
    /// - [`SENDER_NOT_REGISTERED`](client::errors::SENDER_NOT_REGISTERED):
    /// Thrown if `sender_addr` is not registered in the server.
    /// - [`SenderNotAuthenticated`](client::errors::SenderNotAuthenticated):
    /// Thrown if `sender_addr` is not registered with `sender_private_key` in the server.
    /// - [`RecipientNotRegistered`](client::errors::RecipientNotRegistered):
    /// Thrown if `recipient_addr` is not registered in the server.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `sender_addr`.
    fn open_channel(
        self: @T,
        sender_addr: ContractAddress,
        sender_private_key: felt252,
        recipient_addr: ContractAddress,
        token: ContractAddress,
        random: felt252,
    ) -> (ContractAddress, EncChannelInfo, felt252);

    // TODO: Re-read preconditions after implementing the create and use notes function.
    /// Validates `notes_to_create` are a valid redistribution of funds from `notes_to_use`.
    ///
    /// A transfer consists of nullifying notes owned by `owner_addr` and creating
    /// new notes for the recipients.
    /// The owner can be one of the recipients.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The owner's address.
    /// - `owner_private_key` (`felt252`) - The owner's private key.
    /// - `notes_to_use` (`Span<NotePath>`) - The notes that are consumed as part of the transfer.
    /// Must not be empty.
    /// - `notes_to_create` (`Span<NewNote>`) - The notes that are created as a result of the
    /// transfer.
    /// Must not be empty.
    ///
    /// #### Returns
    /// - (`Span<felt252>`) - The nullifiers of `notes_to_use`.
    /// - (`Span<EncNote>`) - An encrypted representation of `notes_to_create`.
    ///
    /// #### Preconditions
    /// - `owner_addr` is registered with `owner_private_key` in the server.
    /// - Each recipient is registered in the server.
    /// - A channel exists from `owner_addr` to each recipient.
    /// - `notes_to_use` use valid channels and indexes.
    /// - The sum of the amounts of `notes_to_create` equals the sum of the amounts of
    /// `notes_to_use`.
    /// - All notes are in the same token.
    /// - All notes in `notes_to_create` have amounts greater than zero.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](client::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY):
    /// Thrown if `owner_private_key` is zero.
    /// - [`NO_NOTES_TO_USE`](client::errors::NO_NOTES_TO_USE):
    /// Thrown if `notes_to_use` is empty.
    /// - [`NO_NOTES_TO_CREATE`](client::errors::NO_NOTES_TO_CREATE):
    /// Thrown if `notes_to_create` is empty.
    /// - [`ZERO_RECIPIENT`](client::errors::ZERO_RECIPIENT):
    /// Thrown if there's a note to be created with zero as the recipient.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN):
    /// Thrown if there's a note to be created with zero as the token.
    /// - [`ZERO_AMOUNT`](client::errors::ZERO_AMOUNT):
    /// Thrown if there's a note to be created with zero as the amount.
    /// - [`NOTE_SUM_MISMATCH`](client::errors::NOTE_SUM_MISMATCH):
    /// Thrown if there's a mismatch between the spent funds and the received funds.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `owner_addr`.
    fn transfer(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        notes_to_use: Span<NotePath>,
        notes_to_create: Span<NewNote>,
    ) -> (Span<felt252>, Span<EncNote>);

    /// Generates a deposit transaction to create a new note for the owner.
    ///
    /// This function prepares the inputs for the `deposit` function in the server.
    /// It encrypts a new note for `owner_addr` (who must be the recipient) with the specified
    /// `note` details.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The address of the note owner (sender of the deposit).
    /// Must not be zero. // TODO: Consider using `note.recipient_addr` instead.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `note` (`NewNote`) - The details of the note to be created.
    /// `note.recipient_addr` must be equal to `owner_addr`.
    /// All `note` fields must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The recipient of the note (owner).
    /// - (`ContractAddress`) - The token address.
    /// - (`u128`) - The amount to deposit.
    /// - (`EncNote`) - The encrypted note to be stored. // TODO: Figure out external notes.
    ///
    /// #### Preconditions
    /// - A self-channel exists for `owner_addr` with `note.token`.
    /// - `note.index == 0` or note `note.index - 1` exists in the self-channel.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`NON_SELF_DEPOSIT`](client::errors::NON_SELF_DEPOSIT): Thrown if `owner_addr` is not the
    /// recipient.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if
    /// `note.recipient_addr` is zero.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if `note.token` is zero.
    /// - [`ZERO_AMOUNT`](client::errors::ZERO_AMOUNT): Thrown if `note.amount` is zero.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `note.recipient_addr` is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](client::errors::CHANNEL_NOT_FOUND): Thrown if a self-channel for
    /// `owner_addr` with `token` does not exist.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](client::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if
    /// `note.index` is not sequential (`note.index != 0` and `note.index - 1` does not exist).
    ///
    /// #### Access Control
    /// - TODO
    fn deposit(
        self: @T, owner_addr: ContractAddress, owner_private_key: felt252, note: NewNote,
    ) -> (ContractAddress, ContractAddress, u128, EncNote);
}
