use client::objects::{NewNote, NotePath};
// TODO: Find out if this can be removed while keeping link in docs.
pub use server;
use server::objects::{EncChannelInfo, EncNote};
use starknet::ContractAddress;

// TODO: Use same naming convention for the functions. (owner/sender,
// private_key/sender_private_key, etc).
#[starknet::interface]
pub trait IClient<T> {
    /// Opens a new channel from `sender_addr` to `recipient_addr`.
    ///
    /// A channel allows a sender to transfer funds to a recipient. It is one-directional and
    /// supports a single token. Only the sender can open a channel.
    ///
    /// #### Parameters
    /// - `sender_addr` (`ContractAddress`) - The address of the sender. Must not be zero.
    /// - `sender_private_key` (`felt252`) - The sender's private key. Must not be zero and must be
    /// canonical.
    /// - `recipient_addr` (`ContractAddress`) - The address of the recipient. Must not be zero.
    /// - `token` (`ContractAddress`) - The address of the token. Must not be zero.
    /// - `random` (`felt252`) - A random value (generated by the sender). Must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The recipient's address.
    /// - ([`EncChannelInfo`](server::objects::EncChannelInfo)) - The encrypted channel information.
    /// - (`felt252`) - The channel id.
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - `sender_addr` is registered with `sender_private_key` in the server.
    /// - `sender_private_key` must be canonical (less than CURVE_ORDER / 2).
    /// - `recipient_addr` is registered in the server.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_SENDER_ADDR`](client::errors::ZERO_SENDER_ADDR): Thrown if `sender_addr` is zero.
    /// - [`ZERO_SENDER_PRIVATE_KEY`](client::errors::ZERO_SENDER_PRIVATE_KEY): Thrown if
    /// `sender_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if `recipient_addr`
    /// is zero.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_RANDOM`](client::errors::ZERO_RANDOM): Thrown if `random` is zero.
    /// - [`PRIVATE_KEY_NOT_CANONICAL`](client::errors::PRIVATE_KEY_NOT_CANONICAL): Thrown if
    /// `sender_private_key` is not canonical.
    /// - [`SENDER_NOT_REGISTERED`](client::errors::SENDER_NOT_REGISTERED): Thrown if `sender_addr`
    /// is not registered in the server.
    /// - [`SENDER_NOT_AUTHENTICATED`](client::errors::SENDER_NOT_AUTHENTICATED): Thrown if
    /// `sender_addr` is not registered with `sender_private_key` in the server.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `recipient_addr` is not registered in the server.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `sender_addr`.
    fn open_channel(
        self: @T,
        sender_addr: ContractAddress,
        sender_private_key: felt252,
        recipient_addr: ContractAddress,
        token: ContractAddress,
        random: felt252,
    ) -> (ContractAddress, EncChannelInfo, felt252);

    // TODO: Add index out of bounds error?
    /// Validates `notes_to_create` are a valid redistribution of funds from `notes_to_use`.
    ///
    /// A transfer consists of nullifying existing notes owned by `owner_addr` and creating
    /// new notes for the recipients.
    /// The owner can be one of the recipients.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The owner's address. Must not be zero.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `notes_to_use` (`Span<`[`NotePath`](client::objects::NotePath)`>`) - The notes that are
    /// consumed as part of the transfer.
    /// Must not be empty.
    /// - `notes_to_create` (`Span<`[`NewNote`](client::objects::NewNote)`>`) - The notes that are
    /// created as a result of the transfer. Must not be empty and have non-zero `recipient_addr`s,
    /// `token`s, and `amount`s.
    ///
    /// #### Returns
    /// - (`Span<felt252>`) - The nullifiers of `notes_to_use`.
    /// - (`Span<`[`EncNote`](EncNote)`>`) - An encrypted representation of `notes_to_create`.
    ///
    /// #### Preconditions
    /// - `owner_addr`, `owner_private_key` must not be zero.
    /// - `notes_to_use`, `notes_to_create` must not be empty.
    /// - `notes_to_use` use valid channel and note indexes of the owner's existing notes.
    /// - `notes_to_create` have non-zero `recipient_addr`s, `token`s, and `amount`s.
    /// - Each recipient is registered in the server.
    /// - A channel exists from `owner_addr` to each recipient of the given token.
    /// - `notes_to_create` use valid (sequential) `index`s within the channel.
    /// - `owner_private_key` matches the `owner_addr`'s public key defined as part of the channels.
    /// - The sum of the amounts of `notes_to_create` equals the sum of the amounts of
    /// `notes_to_use`.
    /// - All notes are in the same token.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](client::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`NO_NOTES_TO_USE`](client::errors::NO_NOTES_TO_USE): Thrown if `notes_to_use` is empty.
    /// - [`NO_NOTES_TO_CREATE`](client::errors::NO_NOTES_TO_CREATE): Thrown if `notes_to_create` is
    /// empty.
    /// - [`NOTE_NOT_FOUND`](client::errors::NOTE_NOT_FOUND): Thrown if a note to be used is not
    /// found.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if there's a note to
    /// be created with zero as the recipient.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if there's a note to be created with
    /// zero as the token.
    /// - [`ZERO_AMOUNT`](client::errors::ZERO_AMOUNT): Thrown if there's a note to be created with
    /// zero as the amount.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if a
    /// recipient is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](client::errors::CHANNEL_NOT_FOUND): Thrown if a channel is not found
    /// for one of the `notes_to_create`.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](client::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if a note
    /// index is not sequential for one of the `notes_to_create`.
    /// - [`NOTE_SUM_MISMATCH`](client::errors::NOTE_SUM_MISMATCH): Thrown if there's a mismatch
    /// between the spent funds and the received funds.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `owner_addr`.
    fn transfer(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        notes_to_use: Span<NotePath>,
        notes_to_create: Span<NewNote>,
    ) -> (Span<felt252>, Span<EncNote>);

    /// Generates a deposit transaction to create a new note for the owner.
    ///
    /// Prepares the inputs for the server's `deposit` function.
    /// `new_note.recipient_addr` is considered the owner, and used as the address to transfer the
    /// deposit from.
    /// The function encrypts a new note for the owner based on the provided details.
    ///
    /// #### Parameters
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `new_note` ([`NewNote`](client::objects::NewNote)) - The details of the note to be
    /// created.
    /// `new_note.recipient_addr`, `new_note.token`, and `new_note.amount` must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The address to transfer the deposit from.
    /// - (`ContractAddress`) - The token address.
    /// - (`u128`) - The amount to deposit.
    /// - ([`EncNote`](server::objects::EncNote)) - The encrypted note to be stored.
    ///
    /// #### Preconditions
    /// - A self-channel exists for `new_note.recipient_addr` with `new_note.token` for
    /// `owner_private_key`'s public key.
    /// - `owner_private_key` matches the `new_note.recipient_addr`'s public key.
    /// - `new_note.index` is sequential within the channel.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](client::errors::ZERO_RECIPIENT_ADDR): Thrown if
    /// `new_note.recipient_addr` is zero.
    /// - [`ZERO_TOKEN`](client::errors::ZERO_TOKEN): Thrown if `new_note.token` is zero.
    /// - [`ZERO_AMOUNT`](client::errors::ZERO_AMOUNT): Thrown if `new_note.amount` is zero.
    /// - [`RECIPIENT_NOT_REGISTERED`](client::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `new_note.recipient_addr` is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](client::errors::CHANNEL_NOT_FOUND): Thrown if a self-channel for
    /// `new_note.recipient_addr` with `new_note.token` doesn't exist with the given
    /// `owner_private_key`.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](client::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if
    /// `new_note.index` is not sequential (`new_note.index != 0` and `new_note.index - 1` does not
    /// exist).
    ///
    /// #### Access Control
    /// - TODO
    fn deposit(
        self: @T, owner_private_key: felt252, new_note: NewNote,
    ) -> (ContractAddress, ContractAddress, u128, EncNote);

    /// Validates a withdrawal of a note and generates the nullifier and withdrawal details for the
    /// server.
    ///
    /// Only a single note can be withdrawn at a time, and it's entire amount must be withdrawn.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The address of the note owner. Must not be zero.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `withdrawal_target` (`ContractAddress`) - The address where the funds will be withdrawn
    /// to. Must not be zero.
    /// - `note_to_withdraw` ([`NotePath`](client::objects::NotePath)) - The note to be withdrawn.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The address to transfer the withdrawn funds to.
    /// - (`ContractAddress`) - The token address.
    /// - (`u128`) - The withdrawal amount.
    /// - (`felt252`) - The nullifier of the note.
    ///
    /// #### Preconditions
    /// - `owner_addr`, `owner_private_key`, and `withdrawal_target` are not zero.
    /// - `owner_private_key`` matches the `owner_addr`'s public key that composes the note's
    /// channel.
    /// - The note exists and belongs to the owner.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](client::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](client::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`ZERO_WITHDRAWAL_TARGET`](client::errors::ZERO_WITHDRAWAL_TARGET): Thrown if
    /// `withdrawal_target` is zero.
    /// - [`NOTE_NOT_FOUND`](client::errors::NOTE_NOT_FOUND): Thrown if the note is not found.
    /// // TODO - Consider adding "Index out of bounds".
    ///
    /// #### Access Control
    /// - TODO
    fn withdraw(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        withdrawal_target: ContractAddress,
        note_to_withdraw: NotePath,
    ) -> (ContractAddress, ContractAddress, u128, felt252);

    /// Replaces the caller's public viewing key to a new value.
    ///
    /// **Notes that were created before updating your public key remain encrypted with the old key
    /// and are not automatically re-encrypted or migrated. These notes can only be accessed using
    /// the private key that was previously associated with your account. To use your new public
    /// key, the sender must open new channels with you.**
    ///
    /// #### Parameters
    /// - `user_addr` (`ContractAddress`) - The user's address. Must not be zero.
    /// - `private_key` (`felt252`) - The user's private key. Must not be zero and must be
    /// canonical.
    ///
    /// #### Returns
    /// - (`felt252`) - The derived public key.
    ///
    /// #### Preconditions
    /// - `user_addr` must not be zero.
    /// - `private_key` must not be zero.
    /// - `private_key` must be canonical (0 < private_key < curve_order/2).
    /// - The user must already be registered in the server.
    /// - `private_key` must match the user's current public key in the server.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_USER_ADDR`](client::errors::ZERO_USER_ADDR): Thrown if `user_addr` is zero.
    /// - [`ZERO_PRIVATE_KEY`](client::errors::ZERO_PRIVATE_KEY): Thrown if `private_key` is zero.
    /// - [`PRIVATE_KEY_NOT_CANONICAL`](client::errors::PRIVATE_KEY_NOT_CANONICAL): Thrown if
    /// `private_key` is not canonical.
    /// - [`USER_NOT_REGISTERED`](client::errors::USER_NOT_REGISTERED): Thrown if the user is not
    /// registered in the server.
    /// - [`USER_NOT_AUTHENTICATED`](client::errors::USER_NOT_AUTHENTICATED): Thrown if the
    /// `private_key` does not match the user's current public key.
    ///
    /// #### Access Control
    /// - Can be called by anyone.
    fn replace_public_key(self: @T, user_addr: ContractAddress, private_key: felt252) -> felt252;
}
