//! RPC backend tests.
//!
//! Run with: `cargo test -p discovery-service --test rpc_backend_tests`
//!
//! These tests verify the RPC backend can correctly query on-chain state.
//!
//! The devnet-dump.json.gz fixture is generated by SDK tests:
//! `DUMP_DEVNET_PATH=../crates/discovery-service/tests/fixtures/devnet-dump.json.gz npm test`

mod common;

use common::setup_devnet_with_dump;
use discovery_core::privacy_pool::views::IViews;
use discovery_core::storage_backend::StorageBackend;
use discovery_service::rpc_backend::{RpcBackend, RpcConfig};
use expect_test::expect;
use starknet_core::types::Felt;
use url::Url;

/// Test that RPC backend can query public keys from contract storage.
#[tokio::test]
async fn test_public_key_lookup() {
    let (devnet, metadata) = setup_devnet_with_dump().await;

    let backend = RpcBackend::new(RpcConfig::new(
        Url::parse(&devnet.rpc_url()).unwrap(),
        metadata.contract_address,
    ))
    .unwrap();

    let snapshot = backend.snapshot(None).await.unwrap();

    // Alice should have a registered public key
    let alice_pubkey = snapshot
        .get_public_key(metadata.alice_address)
        .await
        .unwrap();
    expect![[r#"
        0x07913e4dbbc06e873598f6e0bb0076449079fbdd951650c7f7a258d1c6b6a82d
    "#]]
    .assert_eq(&format!("{:#066x}\n", alice_pubkey));

    // Random address should have no public key (zero)
    let random_pubkey = snapshot
        .get_public_key(Felt::from_hex("0xdeadbeef").unwrap())
        .await
        .unwrap();
    assert_eq!(random_pubkey, Felt::ZERO);
}
