apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-prover-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: transaction-prover
data:
  config.json: |
    {{- include "privacy-starknet.transactionProver.configJson" . | nindent 4 }}
