{{- $sidecar := include "privacy-starknet.componentValues" (list . "transactionProver" "proofInterceptor") | fromYaml -}}
{{- if $sidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: proof-interceptor-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: transaction-prover
data:
  {{- include "privacy-starknet.proofInterceptor.env" . | nindent 2 }}
{{- end }}
