{{- $prover := include "privacy-starknet.componentValues" (list . "transactionProver") | fromYaml -}}
{{- if $prover.service }}
apiVersion: v1
kind: Service
metadata:
  name: transaction-prover
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: transaction-prover
  {{- with $prover.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $prover.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ $prover.config.port }}
      protocol: TCP
      targetPort: {{ $prover.config.port }}
  selector:
    app: transaction-prover
{{- end }}
