{{- $discovery := include "privacy-starknet.componentValues" (list . "discoveryService") | fromYaml -}}
{{- if and $discovery.backendConfig $discovery.backendConfig.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: discovery-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: discovery-service
spec:
  healthCheck:
    type: {{ $discovery.backendConfig.healthCheck.type | default "HTTP" }}
    {{- with $discovery.backendConfig.healthCheck.requestPath }}
    requestPath: {{ . }}
    {{- end }}
    {{- with $discovery.backendConfig.healthCheck.port }}
    port: {{ . }}
    {{- end }}
{{- end }}
