apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: discovery-service
data:
  config.toml: |
    {{- include "privacy-starknet.discoveryService.configToml" . | nindent 4 }}
