{{- $discovery := include "privacy-starknet.componentValues" (list . "discoveryService") | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: discovery-service
data:
  config.toml: |
    [api]
    health_max_lag_secs = {{ $discovery.config.api.health_max_lag_secs }}
    {{- if $discovery.ohttp.enabled }}
    [ohttp]
    enabled = true
    {{- end }}
