{{- $discovery := include "privacy-starknet.componentValues" (list . "discoveryService") | fromYaml -}}
{{- if $discovery.service }}
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-starknet.labels" . | nindent 4 }}
    app: discovery-service
  {{- with $discovery.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $discovery.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $discovery.containerPort }}
      protocol: TCP
      targetPort: {{ $discovery.containerPort }}
  selector:
    app: discovery-service
{{- end }}
