/**
 * Tests for ProofFacts serialization compatibility between TypeScript and Cairo.
 *
 * Reference vectors are generated by the Cairo test:
 *   snforge test generate_reference_proof_facts --include-ignored
 */

import { describe, it, expect } from "vitest";
import { buildProofFacts } from "../../src/utils/proof-facts.js";
import { shortStringToFelt } from "../../src/utils/crypto.js";
import { hash, constants } from "starknet";
import referenceData from "../fixtures/cairo-reference-data.json" with { type: "json" };

describe("ProofFacts Compatibility with Cairo", () => {
  const { proofFacts: reference } = referenceData;

  it("shortStringToFelt matches Cairo constants", () => {
    expect(`0x${shortStringToFelt("VIRTUAL_SNOS").toString(16)}`).toBe(reference.virtualSnos);
    expect(`0x${shortStringToFelt("VIRTUAL_SNOS0").toString(16)}`).toBe(reference.virtualSnos0);
  });

  it("buildProofFacts computes correct message hash", () => {
    const proofFacts = buildProofFacts(
      reference.poolAddress,
      reference.poolClassHash,
      reference.serializedActions,
      BigInt(reference.baseBlockNumber),
      "0x0",
      constants.StarknetChainId.SN_SEPOLIA
    );

    // The last element is the message hash (after the Span length prefix "0x1")
    const messageHash = proofFacts[proofFacts.length - 1];
    expect(messageHash).toBe(reference.messageHash);
  });

  it("computes correct virtual OS config hash for Sepolia", () => {
    const STARKNET_OS_CONFIG_HASH_VERSION = "0x537461726b6e65744f73436f6e66696733";
    const STRK_FEE_TOKEN = "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d";

    const expectedConfigHash = hash.computeHashOnElements([
      STARKNET_OS_CONFIG_HASH_VERSION,
      constants.StarknetChainId.SN_SEPOLIA,
      STRK_FEE_TOKEN,
    ]);

    const proofFacts = buildProofFacts(
      reference.poolAddress,
      reference.poolClassHash,
      reference.serializedActions,
      BigInt(reference.baseBlockNumber),
      "0x0",
      constants.StarknetChainId.SN_SEPOLIA
    );

    // [6] is starknet_os_config_hash
    expect(proofFacts[6]).toBe(expectedConfigHash);
  });

  it("buildProofFacts produces correct layout", () => {
    const proofFacts = buildProofFacts(
      reference.poolAddress,
      reference.poolClassHash,
      reference.serializedActions,
      BigInt(reference.baseBlockNumber),
      "0x0",
      constants.StarknetChainId.SN_SEPOLIA
    );

    expect(proofFacts).toHaveLength(9);
    expect(proofFacts[0]).toBe(`0x${shortStringToFelt("PROOF0").toString(16)}`); // proof_version
    expect(proofFacts[1]).toBe(reference.virtualSnos); // program_variant
    // [2] = virtual_program_hash
    expect(proofFacts[3]).toBe(reference.virtualSnos0); // starknet_os_output_version
    expect(proofFacts[4]).toBe(`0x${BigInt(reference.baseBlockNumber).toString(16)}`); // base_block_number
    expect(proofFacts[7]).toBe("0x1"); // message_to_l1_hashes length
    expect(proofFacts[8]).toBe(reference.messageHash); // message hash
  });
});
