pub const ZERO_RECIPIENT_ADDR: felt252 = 'ZERO_RECIPIENT_ADDR';
pub const ZERO_ENC_CHANNEL_INFO: felt252 = 'ZERO_ENC_CHANNEL_INFO';
pub const ZERO_CHANNEL_HASH: felt252 = 'ZERO_CHANNEL_HASH';
pub const CHANNEL_ALREADY_EXISTS: felt252 = 'CHANNEL_ALREADY_EXISTS';

pub const ZERO_NOTE_ID: felt252 = 'ZERO_NOTE_ID';
pub const ZERO_ENC_NOTE_VALUE: felt252 = 'ZERO_ENC_NOTE_VALUE';
pub const NOTE_ALREADY_EXISTS: felt252 = 'NOTE_ALREADY_EXISTS';
