use core::num::traits::Zero;
use privacy::objects::EncChannelInfo;
use privacy::utils::constants::{OPEN_NOTE_SALT, TWO_POW_120};
use privacy::{errors, events};
use starknet::ContractAddress;

pub(crate) trait InputValidation<T> {
    fn assert_valid(self: T);
}

/// Input for the `SetViewingKey` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SetViewingKeyInput {
    /// A random value used to encrypt the private key for the compliance. Generated by the user.
    pub random: felt252,
}

pub(crate) impl SetViewingKeyInputValid of InputValidation<SetViewingKeyInput> {
    fn assert_valid(self: SetViewingKeyInput) {
        let SetViewingKeyInput { random } = self;
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `OpenChannel` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenChannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel index within the sender's outgoing channels.
    pub index: usize,
    /// A random value used to encrypt the channel info for the recipient. Generated by the sender.
    pub random: felt252,
    /// A salt generated by the sender. Used to guarantee one-time key usage for the encrypted
    /// outgoing channel info.
    pub salt: felt252,
}

pub(crate) impl OpenChannelInputValid of InputValidation<OpenChannelInput> {
    fn assert_valid(self: OpenChannelInput) {
        let OpenChannelInput {
            recipient_addr, recipient_public_key, index: _, random, salt,
        } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
    }
}

/// Input for the `OpenSubchannel` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same subchannel id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenSubchannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel key of the subchannel.
    pub channel_key: felt252,
    /// The index of the subchannel within the channel.
    pub index: usize,
    /// The token of the subchannel.
    pub token: ContractAddress,
    /// A salt used to encrypt the subchannel token. Generated by the sender.
    pub salt: felt252,
}

pub(crate) impl OpenSubchannelInputValid of InputValidation<OpenSubchannelInput> {
    fn assert_valid(self: OpenSubchannelInput) {
        let OpenSubchannelInput {
            recipient_addr, recipient_public_key, channel_key, index: _, token, salt,
        } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(channel_key.is_non_zero(), errors::ZERO_CHANNEL_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
    }
}

/// Input for the `CreateEncNote` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same note id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateEncNoteInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A salt generated by the sender to guarantee one-time key usage.
    /// Must be 120 bits and > OPEN_NOTE_SALT (=1).
    /// (`salt = 1` is reserved for the open (non-encrypted) note, and `salt = 0` indicates the note
    /// does not exist.)
    pub salt: u128,
}

pub(crate) impl CreateEncNoteInputValid of InputValidation<CreateEncNoteInput> {
    fn assert_valid(self: CreateEncNoteInput) {
        let CreateEncNoteInput {
            recipient_addr, recipient_public_key, token, amount: _, index: _, salt,
        } = self;
        // Zero `amount` is allowed to enable note creation on reverted transaction indexes,
        // preventing data leakage from index reuse after a revert.
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
        assert(salt > OPEN_NOTE_SALT, errors::SALT_TOO_SMALL);
        assert(salt < TWO_POW_120, errors::SALT_EXCEEDS_120_BITS);
    }
}

/// Input for the `CreateOpenNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateOpenNoteInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    pub index: usize,
    /// The address of the contract permitted to deposit into the note.
    pub depositor: ContractAddress,
    /// A random value used to encrypt the recipient address for the compliance. Generated by the
    /// sender.
    pub random: felt252,
}

pub(crate) impl CreateOpenNoteInputValid of InputValidation<CreateOpenNoteInput> {
    fn assert_valid(self: CreateOpenNoteInput) {
        let CreateOpenNoteInput {
            recipient_addr, recipient_public_key, token, index: _, depositor, random,
        } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(depositor.is_non_zero(), errors::ZERO_DEPOSITOR);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `Deposit` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct DepositInput {
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to deposit.
    pub amount: u128,
}

pub(crate) impl DepositInputValid of InputValidation<DepositInput> {
    fn assert_valid(self: DepositInput) {
        let DepositInput { token, amount } = self;
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(amount.is_non_zero(), errors::ZERO_AMOUNT);
    }
}

/// Input for the `UseNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct UseNoteInput {
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    pub index: usize,
}

pub(crate) impl UseNoteInputValid of InputValidation<UseNoteInput> {
    fn assert_valid(self: UseNoteInput) {
        let UseNoteInput { channel_key, token, index: _ } = self;
        assert(channel_key.is_non_zero(), errors::ZERO_CHANNEL_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
    }
}

/// Input for the `Withdraw` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WithdrawInput {
    /// The address to withdraw to.
    pub to_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to withdraw.
    pub amount: u128,
    /// A random value used to encrypt the user address for the compliance. Generated by the user.
    pub random: felt252,
}

pub(crate) impl WithdrawInputValid of InputValidation<WithdrawInput> {
    fn assert_valid(self: WithdrawInput) {
        let WithdrawInput { to_addr, token, amount, random } = self;
        assert(to_addr.is_non_zero(), errors::ZERO_TO_ADDR);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(amount.is_non_zero(), errors::ZERO_AMOUNT);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `Swap` client action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SwapInput {
    /// The swap executor contract address.
    // TODO: Read from storage.
    pub swap_executor: ContractAddress,
    /// The AMM/DEX contract to call for the swap.
    pub swap_contract: ContractAddress,
    /// The selector of the swap function to call.
    pub swap_selector: felt252,
    /// The calldata to pass to the swap function.
    pub swap_calldata: Span<felt252>,
    /// The token to swap from.
    pub in_token: ContractAddress,
    /// The token to swap to.
    pub out_token: ContractAddress,
    /// The amount to swap.
    pub in_amount: u128,
    /// The channel key for the note to deposit into.
    pub channel_key: felt252,
    /// The index of the note to deposit into within the channel.
    pub index: usize,
    /// A random value used to encrypt the user address for the compliance. Generated by the user.
    pub random: felt252,
}

pub(crate) impl SwapInputValid of InputValidation<SwapInput> {
    fn assert_valid(self: SwapInput) {
        let SwapInput {
            swap_executor,
            swap_contract,
            swap_selector,
            swap_calldata: _,
            in_token,
            out_token,
            in_amount,
            channel_key,
            index: _,
            random,
        } = self;
        assert(swap_executor.is_non_zero(), errors::ZERO_SWAP_EXECUTOR);
        assert(swap_contract.is_non_zero(), errors::ZERO_SWAP_CONTRACT);
        assert(swap_selector.is_non_zero(), errors::ZERO_SWAP_SELECTOR);
        assert(in_token.is_non_zero(), errors::ZERO_IN_TOKEN);
        assert(out_token.is_non_zero(), errors::ZERO_OUT_TOKEN);
        assert(in_amount.is_non_zero(), errors::ZERO_AMOUNT);
        assert(channel_key.is_non_zero(), errors::ZERO_CHANNEL_KEY);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
        assert(in_token != out_token, errors::SWAP_TO_SAME_TOKEN);
    }
}

// TODO: Gets a single random and generate from it new randoms for each action that needs a random.
// TODO: Consider all randoms to be u128/120 bits.
/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAction {
    /// Register a user with a viewing key, or replace the user's viewing key if already registered.
    SetViewingKey: SetViewingKeyInput,
    /// Open a new channel from the user to a recipient.
    OpenChannel: OpenChannelInput,
    /// Open a new subchannel from the user to a recipient.
    OpenSubchannel: OpenSubchannelInput,
    /// Creates a new encrypted note with a specified amount.
    CreateEncNote: CreateEncNoteInput,
    /// Creates a new open note (unencrypted, zero-value note to be filled by a server action).
    /// Open notes enable interactions where the final amount is determined at execution time,
    /// such as AMM swaps or receiving funds directly through bridge transfers.
    CreateOpenNote: CreateOpenNoteInput,
    /// Deposit funds into the contract.
    Deposit: DepositInput,
    /// Uses up a note (creates a nullifier for it).
    UseNote: UseNoteInput,
    /// Withdraw funds from the contract.
    Withdraw: WithdrawInput,
    /// Triggers a swap: transfers input tokens to swap executor and executes swap.
    /// The swap output is deposited into an open note.
    Swap: SwapInput,
}

#[generate_trait]
pub(crate) impl ClientActionImpl of ClientActionTrait {
    const ACCOUNT_PHASE: u8 = 0;
    const CHANNEL_PHASE: u8 = 1;
    const SUBCHANNEL_PHASE: u8 = 2;
    const DEPOSIT_PHASE: u8 = 3;
    const USE_NOTES_PHASE: u8 = 4;
    const CREATE_NOTES_PHASE: u8 = 5;
    const WITHDRAW_PHASE: u8 = 6;
    const SWAP_PHASE: u8 = 7;

    /// Returns the phase associated with this action.
    fn phase(self: @ClientAction) -> u8 {
        match self {
            ClientAction::SetViewingKey(_) => Self::ACCOUNT_PHASE,
            ClientAction::OpenChannel(_) => Self::CHANNEL_PHASE,
            ClientAction::OpenSubchannel(_) => Self::SUBCHANNEL_PHASE,
            ClientAction::Deposit(_) => Self::DEPOSIT_PHASE,
            ClientAction::CreateEncNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::CreateOpenNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::UseNote(_) => Self::USE_NOTES_PHASE,
            ClientAction::Withdraw(_) => Self::WITHDRAW_PHASE,
            ClientAction::Swap(_) => Self::SWAP_PHASE,
        }
    }
}

/// Input for the `WriteOnce` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WriteOnceInput {
    /// The (base) storage address to write to.
    pub storage_address: felt252,
    /// The value to write, stored sequentially starting at the given storage address.
    pub value: Span<felt252>,
}

/// Input for the `AppendToVec` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct AppendToVecInput {
    /// The recipient's address, which is the key of the map in storage.
    pub recipient_addr: ContractAddress,
    /// The channel info to append.
    pub enc_channel_info: EncChannelInfo,
}

/// Input for the `TransferFrom` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferFromInput {
    /// The address to transfer from.
    pub from_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `TransferTo` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferToInput {
    /// The address to transfer to.
    pub to_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `ReadAssert` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct ReadAssertInput {
    /// The storage address to read and assert.
    pub storage_address: felt252,
    /// The expected value.
    pub value: felt252,
}

/// Input for the `SwapWithExecutor` server action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SwapWithExecutorInput {
    /// The swap executor contract address.
    // TODO: Move to storage.
    pub swap_executor: ContractAddress,
    /// The AMM/DEX contract to call for the swap.
    pub swap_contract: ContractAddress,
    /// The selector of the swap function to call.
    pub swap_selector: felt252,
    /// The calldata to pass to the swap function.
    pub swap_calldata: Span<felt252>,
    /// The token address to swap from.
    pub in_token: ContractAddress,
    /// The token address to swap to.
    pub out_token: ContractAddress,
    /// The input amount for swap.
    pub in_amount: u128,
    /// The note id for the open note to deposit into.
    pub note_id: felt252,
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    WriteOnce: WriteOnceInput,
    /// Append a `EncChannelInfo` value to `recipient_addr`'s vector in storage.
    AppendToVec: AppendToVecInput,
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    TransferFrom: TransferFromInput,
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    TransferTo: TransferToInput,
    /// Read and assert that a storage value is equal to a given value.
    ReadAssert: ReadAssertInput,
    /// Emit [`ViewingKeySet`](privacy::events::ViewingKeySet) event.
    EmitViewingKeySet: events::ViewingKeySet,
    /// Emit [`Withdrawal`](privacy::events::Withdrawal) event.
    EmitWithdrawal: events::Withdrawal,
    /// Emit [`Deposit`](privacy::events::Deposit) event.
    EmitDeposit: events::Deposit,
    /// Emit [`OpenNoteCreated`](privacy::events::OpenNoteCreated) event.
    EmitOpenNoteCreated: events::OpenNoteCreated,
    /// Execute a swap via the swap executor contract.
    SwapWithExecutor: SwapWithExecutorInput,
}
