use privacy::errors;
use privacy::objects::{EncChannelInfo, EncPrivateKey, EncSubchannelInfo};
use starknet::ContractAddress;

/// Input for the `SetViewingKey` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SetViewingKeyInput {
    /// The viewing key to set.
    pub private_key: felt252,
    /// A random value used to encrypt the private key for the compliance. Generated by the user.
    pub random: felt252,
}

/// Input for the `OpenChannel` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenChannelInput {
    /// The private key of the sender (the user who is opening the channel).
    pub sender_private_key: felt252,
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// A random value used to encrypt the channel info for the recipient. Generated by the sender.
    pub random: felt252,
}

/// Input for the `OpenSubchannel` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenSubchannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel key of the subchannel.
    pub channel_key: felt252,
    /// The index of the subchannel within the channel.
    // TODO: Consider changing type to u64.
    pub index: usize,
    /// The token of the subchannel.
    pub token: ContractAddress,
    /// A nonce used to encrypt the subchannel token. Generated by the sender.
    pub nonce: felt252,
}

/// Input for the `CreateNote` action.
///
/// Includes a nonce to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same note id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateNoteInput {
    /// The private key of the sender (the user who is creating the note).
    pub sender_private_key: felt252,
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A nonce generated by the sender. Used to guarantee one-time key usage.
    /// Must be 120 bits.
    pub nonce: u128,
}

/// Input for the `Deposit` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct DepositInput {
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to deposit.
    pub amount: u128,
}

/// Input for the `UseNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct UseNoteInput {
    /// The private key of the owner (the user who is using the note).
    pub owner_private_key: felt252,
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    // TODO: Consider changing type to u64.
    pub note_index: usize,
}

/// Input for the `Withdraw` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WithdrawInput {
    /// The target of the withdrawal.
    pub withdrawal_target: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to withdraw.
    pub amount: u128,
}


// TODO: Consider refactoring tuples to named structs in ServerAction.
// TODO: Gets a single random and generate from it new randoms for each action that needs a random.
/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAction {
    // TODO: Consider renaming to SetKey.
    /// Register a user with a viewing key, or replace the user's viewing key if already registered.
    SetViewingKey: SetViewingKeyInput,
    /// Open a new channel from the user to a recipient.
    OpenChannel: OpenChannelInput,
    /// Open a new subchannel from the user to a recipient.
    OpenSubchannel: OpenSubchannelInput,
    /// Creates a new note based on the specified `NewNote`.
    CreateNote: CreateNoteInput,
    /// Deposit funds into the contract.
    Deposit: DepositInput,
    /// Uses up a note (creates a nullifier for it).
    UseNote: UseNoteInput,
    /// Withdraw funds from the contract.
    Withdraw: WithdrawInput,
}

#[generate_trait]
pub(crate) impl ClientActionImpl of ClientActionTrait {
    const ACCOUNT_PHASE: u8 = 0;
    const CHANNEL_PHASE: u8 = 1;
    const SUBCHANNEL_PHASE: u8 = 2;
    const DEPOSIT_PHASE: u8 = 3;
    const USE_NOTES_PHASE: u8 = 4;
    const CREATE_NOTES_PHASE: u8 = 5;
    const WITHDRAW_PHASE: u8 = 6;

    /// Returns the phase that the action is intended for.
    fn intended_phase(self: @ClientAction) -> u8 {
        match self {
            ClientAction::SetViewingKey(_) => Self::ACCOUNT_PHASE,
            ClientAction::OpenChannel(_) => Self::CHANNEL_PHASE,
            ClientAction::OpenSubchannel(_) => Self::SUBCHANNEL_PHASE,
            ClientAction::Deposit(_) => Self::DEPOSIT_PHASE,
            ClientAction::CreateNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::UseNote(_) => Self::USE_NOTES_PHASE,
            ClientAction::Withdraw(_) => Self::WITHDRAW_PHASE,
        }
    }

    /// Asserts that the action is valid for the current phase and updates the phase.
    fn assert_and_set_phase(self: @ClientAction, ref current_phase: u8) {
        let intended_phase = self.intended_phase();
        assert(current_phase <= intended_phase, errors::ACTIONS_OUT_OF_ORDER);

        // Account phase is only allowed 1 action.
        if intended_phase == Self::ACCOUNT_PHASE {
            current_phase = intended_phase + 1;
        } else {
            current_phase = intended_phase;
        }
    }
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: felt252)
    WriteIfZero: (felt252, felt252),
    // TODO: Generalize to any type, Merge with WriteIfZero.
    // TODO: Better naming for this action.
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: EncSubchannelInfo)
    WriteIfZeroSubchannel: (felt252, EncSubchannelInfo),
    /// Write a value to storage.
    /// (storage_address: felt252, new_value: felt252)
    Write: (felt252, felt252),
    // TODO: Generalize to any type, Merge with Write.
    // TODO: Better naming for this action.
    /// Write an `EncPrivateKey` value to storage.
    /// (storage_address: felt252, new_value: EncPrivateKey)
    WritePrivateKey: (felt252, EncPrivateKey),
    // TODO: Generalize to any vector.
    /// Append a `EncChannelInfo` value to (`recipient_addr`, `recipient_public_key`)'s vector in
    /// storage.
    /// (recipient_addr: ContractAddress, recipient_public_key: felt252, enc_channel_info:
    /// EncChannelInfo)
    AppendToVec: (ContractAddress, felt252, EncChannelInfo),
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    /// (sender: ContractAddress, token: ContractAddress, amount: u128)
    TransferFrom: (ContractAddress, ContractAddress, u128),
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    /// (recipient: ContractAddress, token: ContractAddress, amount: u128)
    TransferTo: (ContractAddress, ContractAddress, u128),
    /// Verify that a storage value is equal to a given value.
    /// (storage_address: felt252, value: felt252)
    VerifyValue: (felt252, felt252),
}
