use privacy::objects::{EncChannelInfo, EncOutgoingChannelInfo, EncPrivateKey, EncSubchannelInfo};
use privacy::{errors, events};
use starknet::ContractAddress;

/// Input for the `SetViewingKey` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SetViewingKeyInput {
    /// The viewing key to set.
    pub private_key: felt252,
    /// A random value used to encrypt the private key for the compliance. Generated by the user.
    pub random: felt252,
}

// TODO: Consider merge salt with random.
/// Input for the `OpenChannel` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenChannelInput {
    /// The private key of the sender (the user who is opening the channel).
    pub sender_private_key: felt252,
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel index within the sender's outgoing channels.
    // TODO: Consider changing type to u64.
    pub index: usize,
    /// A random value used to encrypt the channel info for the recipient. Generated by the sender.
    pub random: felt252,
    /// A salt generated by the sender. Used to guarantee one-time key usage for the encrypted
    /// outgoing channel info.
    pub salt: felt252,
}

/// Input for the `OpenSubchannel` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same subchannel key is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenSubchannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel key of the subchannel.
    pub channel_key: felt252,
    /// The index of the subchannel within the channel.
    // TODO: Consider changing type to u64.
    pub index: usize,
    /// The token of the subchannel.
    pub token: ContractAddress,
    /// A salt used to encrypt the subchannel token. Generated by the sender.
    pub salt: felt252,
}

/// Input for the `CreateNote` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same note id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateNoteInput {
    /// The private key of the sender (the user who is creating the note).
    pub sender_private_key: felt252,
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A salt generated by the sender. Used to guarantee one-time key usage.
    /// Must be 120 bits.
    pub salt: u128,
}

/// Input for the `Deposit` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct DepositInput {
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to deposit.
    pub amount: u128,
}

/// Input for the `UseNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct UseNoteInput {
    /// The private key of the owner (the user who is using the note).
    pub owner_private_key: felt252,
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    // TODO: Consider changing type to u64.
    pub note_index: usize,
}

/// Input for the `Withdraw` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WithdrawInput {
    /// The target of the withdrawal.
    pub withdrawal_target: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to withdraw.
    pub amount: u128,
    /// A random value used to encrypt the user address for the compliance. Generated by the user.
    pub random: felt252,
}


// TODO: Gets a single random and generate from it new randoms for each action that needs a random.
/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAction {
    // TODO: Consider renaming to SetKey/Register.
    /// Register a user with a viewing key, or replace the user's viewing key if already registered.
    SetViewingKey: SetViewingKeyInput,
    /// Open a new channel from the user to a recipient.
    OpenChannel: OpenChannelInput,
    /// Open a new subchannel from the user to a recipient.
    OpenSubchannel: OpenSubchannelInput,
    /// Creates a new note based on the specified `NewNote`.
    CreateNote: CreateNoteInput,
    /// Deposit funds into the contract.
    Deposit: DepositInput,
    /// Uses up a note (creates a nullifier for it).
    UseNote: UseNoteInput,
    /// Withdraw funds from the contract.
    Withdraw: WithdrawInput,
}

#[generate_trait]
pub(crate) impl ClientActionImpl of ClientActionTrait {
    const ACCOUNT_PHASE: u8 = 0;
    const CHANNEL_PHASE: u8 = 1;
    const SUBCHANNEL_PHASE: u8 = 2;
    const DEPOSIT_PHASE: u8 = 3;
    const USE_NOTES_PHASE: u8 = 4;
    const CREATE_NOTES_PHASE: u8 = 5;
    const WITHDRAW_PHASE: u8 = 6;

    /// Returns the phase that the action is intended for.
    fn intended_phase(self: @ClientAction) -> u8 {
        match self {
            ClientAction::SetViewingKey(_) => Self::ACCOUNT_PHASE,
            ClientAction::OpenChannel(_) => Self::CHANNEL_PHASE,
            ClientAction::OpenSubchannel(_) => Self::SUBCHANNEL_PHASE,
            ClientAction::Deposit(_) => Self::DEPOSIT_PHASE,
            ClientAction::CreateNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::UseNote(_) => Self::USE_NOTES_PHASE,
            ClientAction::Withdraw(_) => Self::WITHDRAW_PHASE,
        }
    }

    /// Asserts that the action is valid for the current phase and updates the phase.
    fn assert_and_set_phase(self: @ClientAction, ref current_phase: u8) {
        let intended_phase = self.intended_phase();
        assert(current_phase <= intended_phase, errors::ACTIONS_OUT_OF_ORDER);

        // Account phase is only allowed 1 action.
        if intended_phase == Self::ACCOUNT_PHASE {
            current_phase = intended_phase + 1;
        } else {
            current_phase = intended_phase;
        }
    }
}

/// Input for the `WriteIfZero` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WriteIfZeroInput<T> {
    /// The storage address to write to.
    pub storage_address: felt252,
    /// The value to write.
    pub value: T,
}

/// Input for the `AppendToVec` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct AppendToVecInput {
    /// The recipient's address, which is the key of the map in storage.
    pub recipient_addr: ContractAddress,
    /// The channel info to append.
    pub enc_channel_info: EncChannelInfo,
}
/// Input for the `TransferFrom` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferFromInput {
    /// The sender's address.
    pub sender_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `TransferTo` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferToInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `VerifyValue` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct VerifyValueInput {
    /// The storage address to verify.
    pub storage_address: felt252,
    /// The value to verify.
    pub value: felt252,
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    WriteIfZero: WriteIfZeroInput<felt252>,
    // TODO: Generalize to any type, Merge with WriteIfZero.
    // TODO: Better naming for this action.
    /// Verify that a storage value is zero/empty and then write to it.
    WriteIfZeroSubchannel: WriteIfZeroInput<EncSubchannelInfo>,
    // TODO: Merge with WriteIfZeroSubchannel.
    /// Verify that a storage value is zero/empty and then write to it.
    WriteIfZeroOutgoingChannel: WriteIfZeroInput<EncOutgoingChannelInfo>,
    // TODO: Generalize to any type, Merge with WriteIfZero.
    // TODO: Better naming for this action.
    /// Verify that a storage value is zero/empty and then write to it.
    WriteIfZeroPrivateKey: WriteIfZeroInput<EncPrivateKey>,
    /// Append a `EncChannelInfo` value to `recipient_addr`'s vector in storage.
    AppendToVec: AppendToVecInput,
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    TransferFrom: TransferFromInput,
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    TransferTo: TransferToInput,
    /// Verify that a storage value is equal to a given value.
    VerifyValue: VerifyValueInput,
    /// Emit [`ViewingKeySet`](privacy::events::ViewingKeySet) event.
    EmitViewingKeySet: events::ViewingKeySet,
    /// Emit [`Withdrawal`](privacy::events::Withdrawal) event.
    EmitWithdrawal: events::Withdrawal,
}
