use privacy::objects::{EncChannelInfo, EncNote, NewNote, NotePath, ServerAction};
use starknet::ContractAddress;

// TODO: Use same naming convention for the functions. (owner/sender,
// private_key/sender_private_key, etc).
#[starknet::interface]
pub trait IClient<T> {
    /// Opens a new channel from `sender_addr` to `recipient_addr`.
    ///
    /// A channel allows a sender to transfer funds to a recipient. It is one-directional and
    /// supports a single token. Only the sender can open a channel.
    ///
    /// Returns a span containing two actions to open the channel:
    /// 1. `WriteIfZero` - Verifies that the channel does not already exist (storage value is zero)
    ///    and writes `true` to mark the channel as existing. Parameters:
    ///    - `storage_address`: The storage address for `channel_exists[channel_id]`
    ///    - `new_value`: `true` (as felt252)
    /// 2. `AppendToVec` - Appends the encrypted channel information to the recipient's channel
    ///    vector. Parameters:
    ///    - `recipient_addr`: The address of the recipient
    ///    - `enc_channel_info`: The encrypted channel information containing the ephemeral public
    ///      key, encrypted channel key, encrypted token address, and encrypted sender address
    ///
    /// #### Parameters
    /// - `sender_addr` (`ContractAddress`) - The address of the sender. Must not be zero.
    /// - `sender_private_key` (`felt252`) - The sender's private key. Must not be zero and must be
    /// canonical.
    /// - `recipient_addr` (`ContractAddress`) - The address of the recipient. Must not be zero.
    /// - `token` (`ContractAddress`) - The address of the token. Must not be zero.
    /// - `random` (`felt252`) - A random value (generated by the sender). Must not be zero.
    ///
    /// #### Returns
    /// - (`Span<ServerAction>`) - A span containing the WriteIfZero and AppendToVec actions to open
    /// the channel.
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - `sender_addr` is registered with `sender_private_key` in the server.
    /// - `sender_private_key` must be canonical (less than CURVE_ORDER / 2).
    /// - `recipient_addr` is registered in the server.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_SENDER_ADDR`](privacy::errors::ZERO_SENDER_ADDR): Thrown if `sender_addr` is zero.
    /// - [`ZERO_SENDER_PRIVATE_KEY`](privacy::errors::ZERO_SENDER_PRIVATE_KEY): Thrown if
    /// `sender_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](privacy::errors::ZERO_RECIPIENT_ADDR): Thrown if `recipient_addr`
    /// is zero.
    /// - [`ZERO_TOKEN`](privacy::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_RANDOM`](privacy::errors::ZERO_RANDOM): Thrown if `random` is zero.
    /// - [`PRIVATE_KEY_NOT_CANONICAL`](privacy::errors::PRIVATE_KEY_NOT_CANONICAL): Thrown if
    /// `sender_private_key` is not canonical.
    /// - [`SENDER_NOT_REGISTERED`](privacy::errors::SENDER_NOT_REGISTERED): Thrown if `sender_addr`
    /// is not registered in the server.
    /// - [`SENDER_NOT_AUTHENTICATED`](privacy::errors::SENDER_NOT_AUTHENTICATED): Thrown if
    /// `sender_addr` is not registered with `sender_private_key` in the server.
    /// - [`RECIPIENT_NOT_REGISTERED`](privacy::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `recipient_addr` is not registered in the server.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `sender_addr`.
    fn prepare_open_channel(
        self: @T,
        sender_addr: ContractAddress,
        sender_private_key: felt252,
        recipient_addr: ContractAddress,
        token: ContractAddress,
        random: felt252,
    ) -> Span<ServerAction>;

    // TODO: Add index out of bounds error?
    /// Validates `notes_to_create` are a valid redistribution of funds from `notes_to_use`.
    ///
    /// A transfer consists of nullifying existing notes owned by `owner_addr` and creating
    /// new notes for the recipients.
    /// The owner can be one of the recipients.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The owner's address. Must not be zero.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `notes_to_use` (`Span<`[`NotePath`](privacy::objects::NotePath)`>`) - The notes that are
    /// consumed as part of the transfer.
    /// Must not be empty.
    /// - `notes_to_create` (`Span<`[`NewNote`](privacy::objects::NewNote)`>`) - The notes that are
    /// created as a result of the transfer. Must not be empty and have non-zero `recipient_addr`s,
    /// `token`s, and `amount`s.
    ///
    /// #### Returns
    /// - (`Span<felt252>`) - The nullifiers of `notes_to_use`.
    /// - (`Span<`[`EncNote`](EncNote)`>`) - An encrypted representation of `notes_to_create`.
    ///
    /// #### Preconditions
    /// - `owner_addr`, `owner_private_key` must not be zero.
    /// - `notes_to_use`, `notes_to_create` must not be empty.
    /// - `notes_to_use` use valid channel and note indexes of the owner's existing notes.
    /// - `notes_to_create` have non-zero `recipient_addr`s, `token`s, and `amount`s.
    /// - Each recipient is registered in the server.
    /// - A channel exists from `owner_addr` to each recipient of the given token.
    /// - `notes_to_create` use valid (sequential) `index`s within the channel.
    /// - `owner_private_key` matches the `owner_addr`'s public key defined as part of the channels.
    /// - The sum of the amounts of `notes_to_create` equals the sum of the amounts of
    /// `notes_to_use`.
    /// - All notes are in the same token.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](privacy::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](privacy::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`NO_NOTES_TO_USE`](privacy::errors::NO_NOTES_TO_USE): Thrown if `notes_to_use` is empty.
    /// - [`NO_NOTES_TO_CREATE`](privacy::errors::NO_NOTES_TO_CREATE): Thrown if `notes_to_create`
    /// is empty.
    /// - [`NOTE_NOT_FOUND`](privacy::errors::NOTE_NOT_FOUND): Thrown if a note to be used is not
    /// found.
    /// - [`ZERO_RECIPIENT_ADDR`](privacy::errors::ZERO_RECIPIENT_ADDR): Thrown if there's a note to
    /// be created with zero as the recipient.
    /// - [`ZERO_TOKEN`](privacy::errors::ZERO_TOKEN): Thrown if there's a note to be created with
    /// zero as the token.
    /// - [`ZERO_AMOUNT`](privacy::errors::ZERO_AMOUNT): Thrown if there's a note to be created with
    /// zero as the amount.
    /// - [`RECIPIENT_NOT_REGISTERED`](privacy::errors::RECIPIENT_NOT_REGISTERED): Thrown if a
    /// recipient is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](privacy::errors::CHANNEL_NOT_FOUND): Thrown if a channel is not
    /// found for one of the `notes_to_create`.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](privacy::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if a
    /// note index is not sequential for one of the `notes_to_create`.
    /// - [`NOTE_SUM_MISMATCH`](privacy::errors::NOTE_SUM_MISMATCH): Thrown if there's a mismatch
    /// between the spent funds and the received funds.
    ///
    /// #### Access Control
    /// - Can be called by anyone, but the transaction must be signed by `owner_addr`.
    fn prepare_transfer(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        notes_to_use: Span<NotePath>,
        notes_to_create: Span<NewNote>,
    ) -> (Span<felt252>, Span<EncNote>);

    /// Generates a deposit transaction to create a new note for the owner.
    ///
    /// Prepares the inputs for the server's `deposit` function.
    /// `new_note.recipient_addr` is considered the owner, and used as the address to transfer the
    /// deposit from.
    /// The function encrypts a new note for the owner based on the provided details.
    ///
    /// #### Parameters
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `new_note` ([`NewNote`](privacy::objects::NewNote)) - The details of the note to be
    /// created.
    /// `new_note.recipient_addr`, `new_note.token`, and `new_note.amount` must not be zero.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The address to transfer the deposit from.
    /// - (`ContractAddress`) - The token address.
    /// - (`u128`) - The amount to deposit.
    /// - ([`EncNote`](privacy::objects::EncNote)) - The encrypted note to be stored.
    ///
    /// #### Preconditions
    /// - A self-channel exists for `new_note.recipient_addr` with `new_note.token` for
    /// `owner_private_key`'s public key.
    /// - `owner_private_key` matches the `new_note.recipient_addr`'s public key.
    /// - `new_note.index` is sequential within the channel.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_PRIVATE_KEY`](privacy::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`ZERO_RECIPIENT_ADDR`](privacy::errors::ZERO_RECIPIENT_ADDR): Thrown if
    /// `new_note.recipient_addr` is zero.
    /// - [`ZERO_TOKEN`](privacy::errors::ZERO_TOKEN): Thrown if `new_note.token` is zero.
    /// - [`ZERO_AMOUNT`](privacy::errors::ZERO_AMOUNT): Thrown if `new_note.amount` is zero.
    /// - [`RECIPIENT_NOT_REGISTERED`](privacy::errors::RECIPIENT_NOT_REGISTERED): Thrown if
    /// `new_note.recipient_addr` is not registered in the server.
    /// - [`CHANNEL_NOT_FOUND`](privacy::errors::CHANNEL_NOT_FOUND): Thrown if a self-channel for
    /// `new_note.recipient_addr` with `new_note.token` doesn't exist with the given
    /// `owner_private_key`.
    /// - [`NOTE_INDEX_NOT_SEQUENTIAL`](privacy::errors::NOTE_INDEX_NOT_SEQUENTIAL): Thrown if
    /// `new_note.index` is not sequential (`new_note.index != 0` and `new_note.index - 1` does not
    /// exist).
    ///
    /// #### Access Control
    /// - TODO
    fn prepare_deposit(
        self: @T, owner_private_key: felt252, new_note: NewNote,
    ) -> (ContractAddress, ContractAddress, u128, EncNote);

    /// Validates a withdrawal of a note and generates the nullifier and withdrawal details for the
    /// server.
    ///
    /// Only a single note can be withdrawn at a time, and it's entire amount must be withdrawn.
    ///
    /// #### Parameters
    /// - `owner_addr` (`ContractAddress`) - The address of the note owner. Must not be zero.
    /// - `owner_private_key` (`felt252`) - The owner's private key. Must not be zero.
    /// - `withdrawal_target` (`ContractAddress`) - The address where the funds will be withdrawn
    /// to. Must not be zero.
    /// - `note_to_withdraw` ([`NotePath`](privacy::objects::NotePath)) - The note to be withdrawn.
    ///
    /// #### Returns
    /// - (`ContractAddress`) - The address to transfer the withdrawn funds to.
    /// - (`ContractAddress`) - The token address.
    /// - (`u128`) - The withdrawal amount.
    /// - (`felt252`) - The nullifier of the note.
    ///
    /// #### Preconditions
    /// - `owner_addr`, `owner_private_key`, and `withdrawal_target` are not zero.
    /// - `owner_private_key`` matches the `owner_addr`'s public key that composes the note's
    /// channel.
    /// - The note exists and belongs to the owner.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_OWNER_ADDR`](privacy::errors::ZERO_OWNER_ADDR): Thrown if `owner_addr` is zero.
    /// - [`ZERO_OWNER_PRIVATE_KEY`](privacy::errors::ZERO_OWNER_PRIVATE_KEY): Thrown if
    /// `owner_private_key` is zero.
    /// - [`ZERO_WITHDRAWAL_TARGET`](privacy::errors::ZERO_WITHDRAWAL_TARGET): Thrown if
    /// `withdrawal_target` is zero.
    /// - [`NOTE_NOT_FOUND`](privacy::errors::NOTE_NOT_FOUND): Thrown if the note is not found.
    /// // TODO - Consider adding "Index out of bounds".
    ///
    /// #### Access Control
    /// - TODO
    fn prepare_withdraw(
        self: @T,
        owner_addr: ContractAddress,
        owner_private_key: felt252,
        withdrawal_target: ContractAddress,
        note_to_withdraw: NotePath,
    ) -> (ContractAddress, ContractAddress, u128, felt252);
}

#[starknet::interface]
pub trait IServer<T> {
    /// Registers the caller as a new user with the specified public viewing key.
    ///
    /// #### Parameters
    /// - `public_key` (`felt252`): The public viewing key of the user. Must not be zero.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - `public_key` must not be zero.
    /// - Caller must not have already registered a public key.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_PUBLIC_KEY`](privacy::errors::ZERO_PUBLIC_KEY): Thrown if `public_key` is
    /// zero.
    /// - [`NON_ZERO_VALUE`](privacy::errors::NON_ZERO_VALUE): Thrown if the
    /// caller has already registered a public key.
    ///
    /// #### Access Control
    /// - Self-registration only.
    fn register(ref self: T, public_key: felt252);

    /// Replaces the caller's public viewing key to a new value.
    ///
    /// **Notes that were created before updating your public key remain encrypted with the old key
    /// and are not automatically re-encrypted or migrated. These notes can only be accessed using
    /// the private key that was previously associated with your account. To use your new public
    /// key, the sender must open new channels with you.**
    ///
    /// #### Parameters
    /// - `public_key` (`felt252`): The new public viewing key. Must not be zero.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - `public_key` must not be zero.
    /// - Caller must have already registered a public key.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`ZERO_PUBLIC_KEY`](privacy::errors::ZERO_PUBLIC_KEY): Thrown if `public_key` is zero.
    /// - [`ZERO_VALUE`](privacy::errors::ZERO_VALUE): Thrown if the caller has
    /// not registered a public key.
    ///
    /// #### Access Control
    /// - Self-service only. The caller can only replace their own public key.
    fn replace_public_key(ref self: T, public_key: felt252);

    /// Deposits funds into the contract and creates a note.
    ///
    /// #### Parameters
    /// - `user_addr` (`ContractAddress`): The address of the user depositing the funds. Must not be
    /// zero.
    /// - `token` (`ContractAddress`): The address of the token to deposit. Must not be zero.
    /// - `amount` (`u128`): The amount to deposit. Must not be zero.
    /// - `note` (`EncNote`): The encrypted note to create.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - The note must not already exist.
    /// - The user must have approved the contract to spend the amount.
    /// - The user must have enough balance.
    ///
    /// #### Events Emitted
    /// - TODO
    ///
    /// #### Reverts
    /// TODO: Figure out a way to link external errors.
    /// - [`ZERO_USER_ADDR`](privacy::errors::ZERO_USER_ADDR): Thrown if `user_addr` is zero.
    /// - [`ZERO_TOKEN`](privacy::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_AMOUNT`](privacy::errors::ZERO_AMOUNT): Thrown if `amount` is zero.
    /// - [`ZERO_NOTE_ID`](privacy::errors::ZERO_NOTE_ID): Thrown if `note.id` is zero.
    /// - [`ZERO_ENC_NOTE_VALUE`](privacy::errors::ZERO_ENC_NOTE_VALUE): Thrown if
    /// `note.enc_amount` is zero.
    /// - [`NON_ZERO_VALUE`](privacy::errors::NON_ZERO_VALUE): Thrown if the note already
    /// exists.
    /// - [`INSUFFICIENT_ALLOWANCE`]: Thrown if the allowance is insufficient.
    /// - [`INSUFFICIENT_BALANCE`]: Thrown if the balance is insufficient.
    ///
    /// #### Access Control
    /// - TODO
    fn deposit(
        ref self: T,
        user_addr: ContractAddress,
        token: ContractAddress,
        amount: u128,
        note: EncNote,
    );

    /// Transfers funds by nullifying existing notes and creating new ones.
    ///
    /// #### Parameters
    /// - `nullifiers` (`Span<felt252>`): The nullifiers of the notes to be spent.
    /// - `new_notes` (`Span<EncNote>`): The new encrypted notes to be created.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - `nullifiers` must not be empty.
    /// - `new_notes` must not be empty.
    /// - All nullifiers must not be zero and must not already exist.
    /// - All new notes must have non-zero fields and must not already exist.
    ///
    /// #### Events Emitted
    /// - TODO
    ///
    /// #### Reverts
    /// - [`EMPTY_NULLIFIERS`](privacy::errors::EMPTY_NULLIFIERS): Thrown if `nullifiers` is empty.
    /// - [`EMPTY_NEW_NOTES`](privacy::errors::EMPTY_NEW_NOTES): Thrown if `new_notes` is empty.
    /// - [`ZERO_NULLIFIER`](privacy::errors::ZERO_NULLIFIER): Thrown if a nullifier is zero.
    /// - [`ZERO_NOTE_ID`](privacy::errors::ZERO_NOTE_ID): Thrown if a note id is zero.
    /// - [`ZERO_ENC_NOTE_VALUE`](privacy::errors::ZERO_ENC_NOTE_VALUE): Thrown if a note encrypted
    /// amount is zero.
    /// - [`NON_ZERO_VALUE`](privacy::errors::NON_ZERO_VALUE): Thrown if one of the notes or
    /// nullifiers already exist.
    ///
    /// #### Access Control
    /// - TODO
    fn transfer(ref self: T, nullifiers: Span<felt252>, new_notes: Span<EncNote>);

    /// Withdraws funds from the contract and consumes a note.
    ///
    /// #### Parameters
    /// - `recipient_addr` (`ContractAddress`): The address of the recipient receiving the funds.
    /// Must not be zero.
    /// - `token` (`ContractAddress`): The address of the token to withdraw. Must not be zero.
    /// - `amount` (`u128`): The amount to withdraw. Must not be zero.
    /// - `nullifier` (`felt252`): The nullifier of the note to consume. Must not be zero.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - All inputs must not be zero.
    /// - The nullifier must not already exist.
    ///
    /// #### Events Emitted
    /// - TODO
    ///
    /// #### Reverts
    /// - [`ZERO_RECIPIENT_ADDR`](privacy::errors::ZERO_RECIPIENT_ADDR): Thrown if `recipient_addr`
    /// is zero.
    /// - [`ZERO_TOKEN`](privacy::errors::ZERO_TOKEN): Thrown if `token` is zero.
    /// - [`ZERO_AMOUNT`](privacy::errors::ZERO_AMOUNT): Thrown if `amount` is zero.
    /// - [`ZERO_NULLIFIER`](privacy::errors::ZERO_NULLIFIER): Thrown if `nullifier` is zero.
    /// - [`NON_ZERO_VALUE`](privacy::errors::NON_ZERO_VALUE): Thrown if the
    /// nullifier already exists.
    ///
    /// #### Access Control
    /// - TODO
    fn withdraw(
        ref self: T,
        recipient_addr: ContractAddress,
        token: ContractAddress,
        amount: u128,
        nullifier: felt252,
    );

    /// Executes a list of actions atomically.
    ///
    /// #### Parameters
    /// - `actions` (`Span<ServerAction>`): The list of actions to execute.
    ///
    /// #### Returns
    /// None
    ///
    /// #### Preconditions
    /// - TODO
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// - [`NON_ZERO_VALUE`](privacy::errors::NON_ZERO_VALUE): Thrown if
    /// `WriteIfZero` action is executed and the value at the specified storage path already exists.
    /// - [`INSUFFICIENT_BALANCE`]: Thrown if `TransferFrom` action is executed and the sender has
    /// insufficient balance.
    /// - [`INSUFFICIENT_ALLOWANCE`]: Thrown if `TransferFrom` action is executed and the sender has
    /// insufficient allowance.
    ///
    /// #### Access Control
    /// - TODO
    fn execute_actions(ref self: T, actions: Span<ServerAction>);
}

#[starknet::interface]
pub trait IViews<T> {
    /// Checks if a channel exists.
    ///
    /// #### Parameters
    /// - `channel_id` (`felt252`): The id of the channel.
    ///
    /// #### Returns
    /// (`bool`): True if the channel exists in the contract, false otherwise.
    ///
    /// #### Preconditions
    /// None
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn channel_exists(self: @T, channel_id: felt252) -> bool;

    /// Returns the number of open channels for a given recipient.
    ///
    /// #### Parameters
    /// - `recipient_addr` (`ContractAddress`): The address of the recipient of the channels.
    ///
    /// #### Returns
    /// (`u64`): The number of the open channels for the recipient.
    ///
    /// #### Preconditions
    /// None
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn get_num_of_channels(self: @T, recipient_addr: ContractAddress) -> u64;

    // TODO: add "Index out of bounds" in reverts?
    /// Returns the encrepted channel information for a given recipient and channel index.
    ///
    /// #### Parameters
    /// - `recipient_addr` (`ContractAddress`): The address of the recipient.
    /// - `channel_index` (`u64`): The index of the channel within the recipient's channel vector.
    ///
    /// #### Returns
    /// (`EncChannelInfo`): The encrypted channel information.
    ///
    /// #### Preconditions
    /// - `channel_index` must be a valid index within the `recipient_addr`'s channel vector.
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn get_channel_info(
        self: @T, recipient_addr: ContractAddress, channel_index: u64,
    ) -> EncChannelInfo;

    /// Returns the encrypted note value for a given note id.
    ///
    /// #### Parameters
    /// - `note_id` (`felt252`): The id of the note.
    ///
    /// #### Returns
    /// (`felt252`): The encrypted note value.
    ///
    /// #### Preconditions
    /// None
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn get_note(self: @T, note_id: felt252) -> felt252;

    /// Checks if a nullifier exists.
    ///
    /// #### Parameters
    /// - `nullifier` (`felt252`): The nullifier.
    ///
    /// #### Returns
    /// (`bool`): True if the nullifier exists in the contract, false otherwise.
    ///
    /// #### Preconditions
    /// None
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn nullifier_exists(self: @T, nullifier: felt252) -> bool;

    /// Returns the registered public viewing key of the given user address.
    ///
    /// #### Parameters
    /// - `user_addr` (`ContractAddress`): The address whose public key is being queried.
    ///
    /// #### Returns
    /// - (`felt252`): The public key associated with the user, or zero if not registered.
    ///
    /// #### Preconditions
    /// None
    ///
    /// #### Events Emitted
    /// None
    ///
    /// #### Reverts
    /// None
    ///
    /// #### Access Control
    /// - Any address can call this function.
    fn get_public_key(self: @T, user_addr: ContractAddress) -> felt252;
}
