use core::dict::{Felt252Dict, SquashedFelt252DictTrait};
use core::num::traits::Zero;
use starknet::ContractAddress;

// TODO: Optimize.
#[derive(Drop, Debug)]
pub(crate) struct TokenBalances {
    balance_changes: Array<(ContractAddress, bool, u128)>,
}

pub(crate) impl DefaultTokenBalances of Default<TokenBalances> {
    fn default() -> TokenBalances {
        TokenBalances { balance_changes: array![] }
    }
}

#[generate_trait]
pub(crate) impl TokenBalancesImpl of TokenBalancesTrait {
    fn modify_balance(
        ref self: TokenBalances, token: ContractAddress, is_addition: bool, amount: u128,
    ) {
        self.balance_changes.append((token, is_addition, amount));
    }

    fn is_valid(self: @TokenBalances) -> bool {
        let mut final_balances: Felt252Dict<u128> = Default::default();

        for (token, is_addition, amount) in self.balance_changes {
            let token_felt: felt252 = (*token).into();
            let current_balance = final_balances.get(key: token_felt);
            let new_balance = if *is_addition {
                current_balance + *amount
            } else {
                current_balance - *amount
            };
            final_balances.insert(key: token_felt, value: new_balance);
        }

        let balance_entries = final_balances.squash().into_entries();
        for (_, _, final_balance) in balance_entries {
            if final_balance.is_non_zero() {
                return false;
            }
        }
        true
    }
}

/// The path of an existing note in the server storage.
// TODO: Consider renaming.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct NotePath {
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    // TODO: Consider changing type to u64.
    pub note_index: usize,
}

// TODO: Gets a single random in transfer(/deposit) and generate new randoms for each note (remove
// random field from NewNote).
/// A note that is created by the owner and sent to a recipient.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct NewNote {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A random value used to encrypt the note amount, generated by the sender.
    pub random: felt252,
}

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the recipient to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted channel key.
    /// `enc_channel_key = h(CHANNEL_KEY_TAG, rK.x) + channel_key`
    pub enc_channel_key: felt252,
    /// Encrypted sender address.
    /// `enc_sender_addr = h(SENDER_ADDR_TAG, rK.x) + sender_addr`
    pub enc_sender_addr: felt252,
}

// TODO: Move to a different file.
// TODO: Consider implementing is_non_zero() using the Zero trait.
#[generate_trait]
pub impl EncChannelInfoImpl of EncChannelInfoTrait {
    /// Check if all the `EncChannelInfo`'s fields are non-zero.
    fn is_non_zero(self: @EncChannelInfo) -> bool {
        return self.ephemeral_pubkey.is_non_zero()
            && self.enc_channel_key.is_non_zero()
            && self.enc_sender_addr.is_non_zero();
    }
}

/// An encrypted subchannel info, to be written to storage.
// TODO: Explain in doc why the random is needed.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncSubchannelInfo {
    /// A random value generated by the sender.
    // TODO: Consider renaming.
    pub random: felt252,
    /// The encrypted token.
    pub enc_token: felt252,
}

// TODO: Move to a different file.
pub impl EncSubchannelInfoZero of Zero<EncSubchannelInfo> {
    fn zero() -> EncSubchannelInfo {
        EncSubchannelInfo { random: Zero::zero(), enc_token: Zero::zero() }
    }
    /// Check if one of the `EncSubchannelInfo`'s fields is zero.
    fn is_zero(self: @EncSubchannelInfo) -> bool {
        return self.random.is_zero() || self.enc_token.is_zero();
    }
    /// Check if all the `EncSubchannelInfo`'s fields are non-zero.
    fn is_non_zero(self: @EncSubchannelInfo) -> bool {
        !self.is_zero()
    }
}

// TODO: Consider refactoring tuples to named structs in ClientAction and ServerAction.
/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAdminAction {
    /// Register a new user with a public key.
    /// (user_public_key: felt252)
    Register: felt252,
    /// Replace the user's public key with a new value.
    /// (user_public_key: felt252)
    ReplacePublicKey: felt252,
}

#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientChannelAction {
    /// Open a new channel from the user to a recipient.
    /// (user_private_key: felt252, recipient_addr: ContractAddress, recipient_public_key: felt252,
    /// random: felt252)
    OpenChannel: (felt252, ContractAddress, felt252, felt252),
    /// Open a new subchannel from the user to a recipient.
    /// (recipient_addr: ContractAddress, recipient_public_key: felt252, channel_key: felt252,
    /// index: usize, token: ContractAddress, random: felt252)
    OpenSubchannel: (ContractAddress, felt252, felt252, usize, ContractAddress, felt252),
}

#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientTransferAction {
    /// Creates a new note based on the specified `NewNote`.
    /// (user_private_key: felt252, new_note: NewNote)
    CreateNote: (felt252, NewNote),
    /// Deposit funds into the contract.
    /// (token: ContractAddress, amount: u128)
    Deposit: (ContractAddress, u128),
    /// Uses up a note (creates a nullifier for it) based on the specified `NotePath`.
    /// (user_private_key: felt252, note_to_withdraw: NotePath)
    UseNote: (felt252, NotePath),
    /// Withdraw funds from the contract.
    /// (withdrawal_target: ContractAddress, token: ContractAddress, amount: u128)
    Withdraw: (ContractAddress, ContractAddress, u128),
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: felt252)
    WriteIfZero: (felt252, felt252),
    // TODO: Generalize to any type, Merge with WriteIfZero.
    // TODO: Better naming for this action.
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: EncSubchannelInfo)
    WriteIfZeroSubchannel: (felt252, EncSubchannelInfo),
    // TODO: Consider merging with WriteIfZero.
    /// Verify that a storage value is non-zero and then write to it.
    /// (storage_address: felt252, new_value: felt252)
    WriteIfNonZero: (felt252, felt252),
    // TODO: Generalize to any vector.
    /// Append a value to a vector in storage.
    /// (recipient_addr: ContractAddress, recipient_public_key: felt252, enc_channel_info:
    /// EncChannelInfo)
    AppendToVec: (ContractAddress, felt252, EncChannelInfo),
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    /// (sender: ContractAddress, token: ContractAddress, amount: u128)
    TransferFrom: (ContractAddress, ContractAddress, u128),
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    /// (recipient: ContractAddress, token: ContractAddress, amount: u128)
    TransferTo: (ContractAddress, ContractAddress, u128),
    /// Verify that a storage value is equal to a given value.
    /// (storage_address: felt252, value: felt252)
    VerifyValue: (felt252, felt252),
}
