use core::dict::{Felt252Dict, SquashedFelt252DictTrait};
use core::num::traits::Zero;
use privacy::errors;
use starknet::ContractAddress;

#[derive(Drop, Debug)]
pub(crate) enum BalanceOp {
    ADDITION,
    SUBTRACTION,
}

// TODO: Optimize.
#[derive(Drop, Debug)]
pub(crate) struct TokenBalances {
    balance_changes: Array<(ContractAddress, BalanceOp, u128)>,
}

pub(crate) impl DefaultTokenBalances of Default<TokenBalances> {
    fn default() -> TokenBalances {
        TokenBalances { balance_changes: array![] }
    }
}

#[generate_trait]
pub(crate) impl TokenBalancesImpl of TokenBalancesTrait {
    fn modify_balance(
        ref self: TokenBalances, token: ContractAddress, op: BalanceOp, amount: u128,
    ) {
        self.balance_changes.append((token, op, amount));
    }

    fn is_valid(self: @TokenBalances) -> bool {
        let mut final_balances: Felt252Dict<u128> = Default::default();

        for (token, op, amount) in self.balance_changes {
            let token_felt: felt252 = (*token).into();
            let current_balance = final_balances.get(key: token_felt);
            match op {
                BalanceOp::ADDITION => {
                    final_balances.insert(key: token_felt, value: current_balance + *amount);
                },
                BalanceOp::SUBTRACTION => {
                    final_balances.insert(key: token_felt, value: current_balance - *amount);
                },
            };
        }

        let balance_entries = final_balances.squash().into_entries();
        for (_, _, final_balance) in balance_entries {
            if final_balance.is_non_zero() {
                return false;
            }
        }
        true
    }
}

/// The path of an existing note in the server storage.
// TODO: Consider renaming.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct NotePath {
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    // TODO: Consider changing type to u64.
    pub note_index: usize,
}

// TODO: Gets a single random in transfer(/deposit) and generate new randoms for each note (remove
// random field from NewNote).
/// A note that is created by the owner and sent to a recipient.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct NewNote {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A random value used to encrypt the note amount, generated by the sender.
    /// Must be 120 bits.
    pub random: u128,
}

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the recipient to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted channel key.
    /// `enc_channel_key = h(CHANNEL_KEY_TAG, rK.x) + channel_key`
    pub enc_channel_key: felt252,
    /// Encrypted sender address.
    /// `enc_sender_addr = h(SENDER_ADDR_TAG, rK.x) + sender_addr`
    pub enc_sender_addr: felt252,
}

// TODO: Move to a different file.
// TODO: Consider implementing is_non_zero() using the Zero trait.
#[generate_trait]
pub impl EncChannelInfoImpl of EncChannelInfoTrait {
    /// Check if all the `EncChannelInfo`'s fields are non-zero.
    fn is_non_zero(self: @EncChannelInfo) -> bool {
        return self.ephemeral_pubkey.is_non_zero()
            && self.enc_channel_key.is_non_zero()
            && self.enc_sender_addr.is_non_zero();
    }
}

/// Ciphertext for an ECDH-based encryption of private key.
/// Used for compliance to be able to decrypt the private key.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub(crate) struct EncPrivateKey {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the compliance to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted private key.
    /// `enc_private_key = h(ENC_PRIVATE_KEY_TAG, rK.x) + private_key`
    pub enc_private_key: felt252,
}

// TODO: Move to a different file.
pub impl EncPrivateKeyZero of Zero<EncPrivateKey> {
    fn zero() -> EncPrivateKey {
        EncPrivateKey { ephemeral_pubkey: Zero::zero(), enc_private_key: Zero::zero() }
    }
    /// Check if one of the `EncPrivateKey`'s fields is zero.
    fn is_zero(self: @EncPrivateKey) -> bool {
        return self.ephemeral_pubkey.is_zero() || self.enc_private_key.is_zero();
    }
    /// Check if all the `EncPrivateKey`'s fields are non-zero.
    fn is_non_zero(self: @EncPrivateKey) -> bool {
        !self.is_zero()
    }
}

/// An encrypted subchannel info, to be written to storage.
// TODO: Explain in doc why the random is needed.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncSubchannelInfo {
    /// A random value generated by the sender.
    // TODO: Consider renaming.
    pub random: felt252,
    /// The encrypted token.
    pub enc_token: felt252,
}

// TODO: Move to a different file.
pub impl EncSubchannelInfoZero of Zero<EncSubchannelInfo> {
    fn zero() -> EncSubchannelInfo {
        EncSubchannelInfo { random: Zero::zero(), enc_token: Zero::zero() }
    }
    /// Check if one of the `EncSubchannelInfo`'s fields is zero.
    fn is_zero(self: @EncSubchannelInfo) -> bool {
        return self.random.is_zero() || self.enc_token.is_zero();
    }
    /// Check if all the `EncSubchannelInfo`'s fields are non-zero.
    fn is_non_zero(self: @EncSubchannelInfo) -> bool {
        !self.is_zero()
    }
}

// TODO: Consider refactoring tuples to named structs in ClientAction and ServerAction.
/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAction {
    // TODO: Rename user_private_key to private_key here.
    /// Register a new user with a viewing key.
    /// The random is used to encrypt the private key.
    /// (user_private_key: felt252, random: felt252)
    Register: (felt252, felt252),
    // TODO: Rename user_private_key to private_key here.
    /// Replace the user's viewing key with a new key.
    /// (user_private_key: felt252, random: felt252)
    ReplaceKey: (felt252, felt252),
    /// Open a new channel from the user to a recipient.
    /// (user_private_key: felt252, recipient_addr: ContractAddress, recipient_public_key: felt252,
    /// random: felt252)
    OpenChannel: (felt252, ContractAddress, felt252, felt252),
    /// Open a new subchannel from the user to a recipient.
    /// (recipient_addr: ContractAddress, recipient_public_key: felt252, channel_key: felt252,
    /// index: usize, token: ContractAddress, random: felt252)
    OpenSubchannel: (ContractAddress, felt252, felt252, usize, ContractAddress, felt252),
    /// Creates a new note based on the specified `NewNote`.
    /// (user_private_key: felt252, new_note: NewNote)
    CreateNote: (felt252, NewNote),
    /// Deposit funds into the contract.
    /// (token: ContractAddress, amount: u128)
    Deposit: (ContractAddress, u128),
    /// Uses up a note (creates a nullifier for it) based on the specified `NotePath`.
    /// (user_private_key: felt252, note_to_withdraw: NotePath)
    UseNote: (felt252, NotePath),
    /// Withdraw funds from the contract.
    /// (withdrawal_target: ContractAddress, token: ContractAddress, amount: u128)
    Withdraw: (ContractAddress, ContractAddress, u128),
}

#[generate_trait]
pub(crate) impl ClientActionImpl of ClientActionTrait {
    const ACCOUNT_PHASE: u8 = 0;
    const CHANNEL_PHASE: u8 = 1;
    const SUBCHANNEL_PHASE: u8 = 2;
    const DEPOSIT_PHASE: u8 = 3;
    const NOTES_PHASE: u8 = 4;
    const WITHDRAW_PHASE: u8 = 5;

    /// Returns the phase that the action is intended for.
    fn intended_phase(self: @ClientAction) -> u8 {
        match self {
            ClientAction::Register(_) => Self::ACCOUNT_PHASE,
            ClientAction::ReplaceKey(_) => Self::ACCOUNT_PHASE,
            ClientAction::OpenChannel(_) => Self::CHANNEL_PHASE,
            ClientAction::OpenSubchannel(_) => Self::SUBCHANNEL_PHASE,
            ClientAction::Deposit(_) => Self::DEPOSIT_PHASE,
            ClientAction::CreateNote(_) => Self::NOTES_PHASE,
            ClientAction::UseNote(_) => Self::NOTES_PHASE,
            ClientAction::Withdraw(_) => Self::WITHDRAW_PHASE,
        }
    }

    /// Asserts that the action is valid for the current phase and updates the phase.
    fn assert_and_set_phase(self: @ClientAction, ref current_phase: u8) {
        let intended_phase = self.intended_phase();
        assert(current_phase <= intended_phase, errors::ACTIONS_OUT_OF_ORDER);

        // Account phase is only allowed 1 action.
        if intended_phase == Self::ACCOUNT_PHASE {
            current_phase = intended_phase + 1;
        } else {
            current_phase = intended_phase;
        }
    }
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: felt252)
    WriteIfZero: (felt252, felt252),
    // TODO: Generalize to any type, Merge with WriteIfZero.
    // TODO: Better naming for this action.
    /// Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: EncSubchannelInfo)
    WriteIfZeroSubchannel: (felt252, EncSubchannelInfo),
    // TODO: Generalize with WriteIfZeroSubchannel - both structs are similar.
    // TODO: Better naming for this action.
    // Verify that a storage value is zero/empty and then write to it.
    /// (storage_address: felt252, new_value: EncPrivateKey)
    WriteIfZeroPrivateKey: (felt252, EncPrivateKey),
    // TODO: Consider merging with WriteIfZero.
    /// Verify that a storage value is non-zero and then write to it.
    /// (storage_address: felt252, new_value: felt252)
    WriteIfNonZero: (felt252, felt252),
    // TODO: Generalize to any type, Merge with WriteIfNonZero.
    /// Verify that a storage value is non-zero and then write to it.
    /// (storage_address: felt252, new_value: EncPrivateKey)
    WriteIfNonZeroPrivateKey: (felt252, EncPrivateKey),
    // TODO: Generalize to any vector.
    /// Append a `EncChannelInfo` value to (`recipient_addr`, `recipient_public_key`)'s vector in
    /// storage.
    /// (recipient_addr: ContractAddress, recipient_public_key: felt252, enc_channel_info:
    /// EncChannelInfo)
    AppendToVec: (ContractAddress, felt252, EncChannelInfo),
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    /// (sender: ContractAddress, token: ContractAddress, amount: u128)
    TransferFrom: (ContractAddress, ContractAddress, u128),
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    /// (recipient: ContractAddress, token: ContractAddress, amount: u128)
    TransferTo: (ContractAddress, ContractAddress, u128),
    /// Verify that a storage value is equal to a given value.
    /// (storage_address: felt252, value: felt252)
    VerifyValue: (felt252, felt252),
}
