use core::dict::{Felt252Dict, SquashedFelt252Dict, SquashedFelt252DictTrait};
use core::num::traits::Zero;
use privacy::errors;
use starknet::ContractAddress;

pub(crate) type TokenBalances = Felt252Dict<u128>;
pub(crate) type SquashedTokenBalances = SquashedFelt252Dict<u128>;

#[generate_trait]
pub(crate) impl TokenBalancesImpl of TokenBalancesTrait {
    fn add_balance(ref self: TokenBalances, token: ContractAddress, amount: u128) {
        let key = token.into();
        let current_balance = self.get(:key);
        self.insert(:key, value: current_balance + amount);
    }
    fn subtract_balance(ref self: TokenBalances, token: ContractAddress, amount: u128) {
        let key = token.into();
        let current_balance = self.get(:key);
        assert(current_balance >= amount, errors::NEGATIVE_INTERMEDIATE_BALANCE);
        self.insert(:key, value: current_balance - amount);
    }
    fn assert_valid(self: SquashedTokenBalances) {
        for (_token, _, balance) in self.into_entries() {
            // TODO: Add context (token) to the error.
            assert(balance.is_zero(), errors::FINAL_BALANCE_MUST_BE_ZERO);
        }
    }
}

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the recipient to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted channel key.
    /// `enc_channel_key = h(CHANNEL_KEY_TAG, rK.x) + channel_key`
    pub enc_channel_key: felt252,
    /// Encrypted sender address.
    /// `enc_sender_addr = h(SENDER_ADDR_TAG, rK.x) + sender_addr`
    pub enc_sender_addr: felt252,
}

// TODO: Consider implementing is_non_zero() using the Zero trait.
#[generate_trait]
pub impl EncChannelInfoImpl of EncChannelInfoTrait {
    /// Check if all the `EncChannelInfo`'s fields are non-zero.
    fn is_non_zero(self: @EncChannelInfo) -> bool {
        return self.ephemeral_pubkey.is_non_zero()
            && self.enc_channel_key.is_non_zero()
            && self.enc_sender_addr.is_non_zero();
    }
}

/// Ciphertext for an ECDH-based encryption of private key.
/// Used for compliance to be able to decrypt the private key.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub(crate) struct EncPrivateKey {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the compliance to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted private key.
    /// `enc_private_key = h(ENC_PRIVATE_KEY_TAG, rK.x) + private_key`
    pub enc_private_key: felt252,
}

pub impl EncPrivateKeyZero of Zero<EncPrivateKey> {
    fn zero() -> EncPrivateKey {
        EncPrivateKey { ephemeral_pubkey: Zero::zero(), enc_private_key: Zero::zero() }
    }
    /// Check if one of the `EncPrivateKey`'s fields is zero.
    fn is_zero(self: @EncPrivateKey) -> bool {
        return self.ephemeral_pubkey.is_zero() || self.enc_private_key.is_zero();
    }
    /// Check if all the `EncPrivateKey`'s fields are non-zero.
    fn is_non_zero(self: @EncPrivateKey) -> bool {
        !self.is_zero()
    }
}

/// An encrypted subchannel info, to be written to storage.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncSubchannelInfo {
    /// A salt generated by the sender. Used to guarantee one-time key usage.
    pub salt: felt252,
    /// The encrypted token.
    pub enc_token: felt252,
}

pub impl EncSubchannelInfoZero of Zero<EncSubchannelInfo> {
    fn zero() -> EncSubchannelInfo {
        EncSubchannelInfo { salt: Zero::zero(), enc_token: Zero::zero() }
    }
    /// Check if `enc_token` field is zero.
    fn is_zero(self: @EncSubchannelInfo) -> bool {
        return self.enc_token.is_zero();
    }
    /// Check if `enc_token` field is non-zero.
    fn is_non_zero(self: @EncSubchannelInfo) -> bool {
        !self.is_zero()
    }
}

/// Ciphertext for an ECDH-based encryption of user address.
/// Used for compliance to be able to decrypt the user address when withdrawing.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub(crate) struct EncAddress {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the compliance to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted address.
    /// `enc_address = h(ENC_ADDRESS_TAG, rK.x) + address`
    pub enc_address: felt252,
}
