// Renders the committed screening vectors (fixtures/screening-vectors.json,
// produced by the reference TS signer) into a Cairo data module the privacy
// contract's verifier tests consume. The JSON is the source of truth; this
// output is generated — never hand-edit it.
//   node scripts/gen_cairo_screening_vectors.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const fixture = JSON.parse(
  readFileSync(join(repoRoot, "fixtures", "screening-vectors.json"), "utf8"),
);
const outPath = join(repoRoot, "packages", "privacy", "src", "tests", "screening_vectors.cairo");

const hex = (value) => "0x" + BigInt(value).toString(16);
const signerPublicKey = hex(fixture.signer_public_key);

// Emit the exact shape `scarb fmt` produces (8-space struct indent, 12-space
// fields, trailing commas) so the generated file is byte-idempotent without a
// separate format pass.
const field = (name, value) => `            ${name}: ${value},`;

const rows = fixture.vectors
  .map((vector) =>
    [
      "        ScreeningVector {",
      field("chain_id", hex(vector.chain_id)),
      field("depositor", hex(vector.depositor)),
      field("issued_at", vector.issued_at),
      field("signer_public_key", signerPublicKey),
      field("message_hash", hex(vector.message_hash)),
      field("sig_r", hex(vector.sig_r)),
      field("sig_s", hex(vector.sig_s)),
      "        },",
    ].join("\n"),
  )
  .join("\n");

writeFileSync(
  outPath,
  `// @generated by scripts/gen_cairo_screening_vectors.mjs — DO NOT EDIT.
// Source of truth: fixtures/screening-vectors.json (produced by the reference
// TS signer scripts/address_validation_signer/ts). Regenerate and commit:
//   (cd scripts/address_validation_signer/ts && npm run gen-fixtures)
//   node scripts/gen_cairo_screening_vectors.mjs

#[derive(Drop)]
pub struct ScreeningVector {
    pub chain_id: felt252,
    pub depositor: felt252,
    pub issued_at: u64,
    pub signer_public_key: felt252,
    pub message_hash: felt252,
    pub sig_r: felt252,
    pub sig_s: felt252,
}

pub fn screening_vectors() -> Array<ScreeningVector> {
    array![
${rows}
    ]
}
`,
);
console.log(`wrote ${fixture.vectors.length} vectors -> ${outPath}`);
