//! Storage interface for the privacy contract.

use async_trait::async_trait;
use starknet_core::types::BlockId;
use starknet_types_core::felt::Felt;
use thiserror::Error;

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x).
    pub ephemeral_pubkey: Felt,
    /// Encrypted channel key.
    pub enc_channel_key: Felt,
    /// Encrypted sender address.
    pub enc_sender_addr: Felt,
}

/// Ciphertext for an ECDH-based encryption of private key.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncPrivateKey {
    /// Ephemeral ECDH public key x-coordinate (rG.x).
    pub ephemeral_pubkey: Felt,
    /// Encrypted private key.
    pub enc_private_key: Felt,
}

/// Encrypted subchannel info.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncSubchannelInfo {
    /// Salt generated by the sender for one-time key usage.
    pub salt: Felt,
    /// Encrypted token.
    pub enc_token: Felt,
}

/// Errors that can occur during storage operations.
#[derive(Debug, Error)]
pub enum StorageError {
    /// RPC communication error.
    #[error("RPC error: {0}")]
    Rpc(String),
    /// Failed to compute storage slot address.
    #[error("slot computation failed: {0}")]
    SlotComputation(#[from] anyhow::Error),
    /// Failed to establish connection.
    #[error("connection failed: {0}")]
    Connection(String),
}

/// Factory for creating storage snapshots bound to a specific block.
#[async_trait]
pub trait StorageBackend: Send + Sync {
    /// The snapshot type produced by this backend.
    type Snapshot: StorageSnapshot;

    /// Creates a snapshot at the specified block.
    /// If `block_id` is `None`, uses the latest block.
    async fn snapshot(&self, block_id: Option<BlockId>) -> Result<Self::Snapshot, StorageError>;
}

/// Consistent view of storage at a specific block.
#[async_trait]
pub trait StorageSnapshot: IViews {
    /// Returns the block ID this snapshot is bound to.
    fn block_id(&self) -> BlockId;
}

/// Privacy contract view methods
#[async_trait]
pub trait IViews: Send + Sync {
    /// Checks if a channel with the given ID exists.
    async fn channel_exists(&self, channel_id: Felt) -> Result<bool, StorageError>;

    /// Returns the number of channels for a recipient.
    async fn get_num_of_channels(&self, recipient_addr: Felt) -> Result<u64, StorageError>;

    /// Returns channel info for a recipient at the given index.
    async fn get_channel_info(
        &self,
        recipient_addr: Felt,
        channel_index: u64,
    ) -> Result<EncChannelInfo, StorageError>;

    /// Checks if a subchannel with the given ID exists.
    async fn subchannel_exists(&self, subchannel_id: Felt) -> Result<bool, StorageError>;

    /// Returns encrypted subchannel info for the given key.
    async fn get_subchannel_info(
        &self,
        subchannel_key: Felt,
    ) -> Result<EncSubchannelInfo, StorageError>;

    /// Returns the note value for the given note ID.
    async fn get_note(&self, note_id: Felt) -> Result<Felt, StorageError>;

    /// Checks if a nullifier exists.
    async fn nullifier_exists(&self, nullifier: Felt) -> Result<bool, StorageError>;

    /// Returns a user's public viewing key.
    async fn get_public_key(&self, user_addr: Felt) -> Result<Felt, StorageError>;

    /// Returns a user's encrypted private key.
    async fn get_enc_private_key(&self, user_addr: Felt) -> Result<EncPrivateKey, StorageError>;

    /// Returns the compliance public key.
    async fn get_compliance_public_key(&self) -> Result<Felt, StorageError>;
}
