//! Privacy pool specific types.
//!
//! This module contains the data structures used by the privacy pool contract,
//! including encrypted ciphertext types and decrypted plaintext types.

use std::fmt;
use std::ops::Deref;

use serde::{Deserialize, Serialize};
use starknet_types_core::felt::Felt;
use zeroize::Zeroize;

/// Extracts low 128 bits from a Felt.
pub fn felt_low_u128(felt: Felt) -> u128 {
    let d = felt.to_le_digits();
    d[0] as u128 | (d[1] as u128) << 64
}

/// A Felt that automatically zeroes its memory on drop.
///
/// Implements `Deref<Target=Felt>` for transparent use where `&Felt` is expected.
///
/// Deliberately excludes `Copy` (silent copies of secrets are dangerous)
/// and `Serde` (keys should be wrapped at the system boundary, not
/// deserialized directly). `Debug` prints `[REDACTED]` to prevent
/// accidental logging of key material.
#[derive(Clone)]
pub struct SecretFelt(Felt);

impl SecretFelt {
    pub fn new(felt: Felt) -> Self {
        Self(felt)
    }
}

impl Deref for SecretFelt {
    type Target = Felt;
    fn deref(&self) -> &Felt {
        &self.0
    }
}

impl Zeroize for SecretFelt {
    fn zeroize(&mut self) {
        self.0 = Felt::ZERO;
    }
}

impl Drop for SecretFelt {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl fmt::Debug for SecretFelt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[REDACTED]")
    }
}

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x).
    pub ephemeral_pubkey: Felt,
    /// Encrypted channel key.
    pub enc_channel_key: Felt,
    /// Encrypted sender address.
    pub enc_sender_addr: Felt,
}

/// Ciphertext for an ECDH-based encryption of private key.
/// Used by the auditor to decrypt the user's private key.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncPrivateKey {
    /// Auditor public key used for encryption.
    pub auditor_public_key: Felt,
    /// Ephemeral ECDH public key x-coordinate (rG.x).
    pub ephemeral_pubkey: Felt,
    /// Encrypted private key.
    pub enc_private_key: Felt,
}

/// Encrypted subchannel info.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncSubchannelInfo {
    /// Salt generated by the sender for one-time key usage.
    pub salt: Felt,
    /// Encrypted token.
    pub enc_token: Felt,
}

/// Decrypted channel information.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChannelInfo {
    /// The channel key.
    pub channel_key: Felt,
    /// The sender's address.
    pub sender_addr: Felt,
}

/// Encrypted outgoing channel info stored in the contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncOutgoingChannelInfo {
    /// Salt generated by the sender for one-time key usage.
    pub salt: Felt,
    /// Encrypted recipient address.
    pub enc_recipient_addr: Felt,
}
