pub mod Errors {
    pub const NOTE_SUM_MISMATCH: felt252 = 'NOTE_SUM_MISMATCH';
    pub const NOTE_TOKEN_MISMATCH: felt252 = 'NOTE_TOKEN_MISMATCH';
    pub const NOTE_OWNER_MISMATCH: felt252 = 'NOTE_OWNER_MISMATCH';
    pub const EMPTY_TRANSFER_INPUT: felt252 = 'EMPTY_TRANSFER_INPUT';
    pub const EMPTY_TRANSFER_OUTPUT: felt252 = 'EMPTY_TRANSFER_OUTPUT';
    pub const NOTE_AMOUNT_MUST_BE_NON_ZERO: felt252 = 'NOTE_AMOUNT_MUST_BE_NON_ZERO';
    pub const NOTE_TOKEN_ZERO_ADDRESS: felt252 = 'NOTE_TOKEN_ZERO_ADDRESS';
    pub const NOTE_OWNER_ZERO_ADDRESS: felt252 = 'NOTE_OWNER_ZERO_ADDRESS';
}

