pub const NOTE_SUM_MISMATCH: felt252 = 'NOTE_SUM_MISMATCH';
pub const NO_NOTES_TO_USE: felt252 = 'NO_NOTES_TO_USE';
pub const NO_NOTES_TO_CREATE: felt252 = 'NO_NOTES_TO_CREATE';
pub const UNEXPECTED_ZERO_VALUE: felt252 = 'UNEXPECTED_ZERO_VALUE';
pub const SERVER_ZERO_ADDRESS: felt252 = 'SERVER_ZERO_ADDRESS';
