pub const NOTE_SUM_MISMATCH: felt252 = 'NOTE_SUM_MISMATCH';
pub const NO_NOTES_TO_USE: felt252 = 'NO_NOTES_TO_USE';
pub const NO_NOTES_TO_CREATE: felt252 = 'NO_NOTES_TO_CREATE';
pub const SERVER_ZERO_ADDRESS: felt252 = 'SERVER_ZERO_ADDRESS';
pub const NOTE_AMOUNT_MUST_BE_NON_ZERO: felt252 = 'NOTE_AMOUNT_MUST_BE_NON_ZERO';
