name: Cairo CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cairo_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.15.0"

      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.54.1"

      - name: Check formatting
        run: scarb fmt -w --check

      - name: Check unused imports and variables
        run: |
          output=$(scarb build -t 2>&1)
          matches=$(echo "$output" | grep -E "warn: Unused import|warn\[E0001\]: Unused variable" -A 2 || true)
          if [ -n "$matches" ]; then
            echo "Unused imports or variables detected:"
            echo "$matches"
            exit 1
          fi

      - name: Run tests
        run: scarb test

      - name: Cache Cairo build
        uses: actions/cache/save@v4
        with:
          path: target/dev
          key: cairo-build-${{ github.sha }}
