name: Check Formatting

on:
  workflow_call:

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.17.0-rc.1"

      - name: Check formatting
        run: |
          scarb fmt -w --check

      - name: Check unused imports and variables
        run: |
          output=$(scarb build -t 2>&1)
          matches=$(echo "$output" | grep -E "warn: Unused import|warn\[E0001\]: Unused variable" -A 2 || true)
          if [ -n "$matches" ]; then
            echo "Unused imports or variables detected:"
            echo "$matches"
            exit 1
          fi
