name: Check Formatting

on:
  workflow_call:

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.12.2"

      - name: Check formatting
        run: |
          scarb fmt -w --check

      - name: Check unused imports
        run: |
          output=$(scarb build 2>&1)
          if echo "$output" | grep -q "warn: Unused import"; then
            echo "Unused imports detected:"
            echo "$output" | grep "warn: Unused import" -A 2
            exit 1
          fi
