name: Rust CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rust_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust fmt
        run: cargo fmt --all -- --check

      - name: Rust clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Rust build
        run: cargo build --workspace --all-targets

      - name: Rust test
        run: cargo test --workspace --all-targets
