name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.17.0-rc.1"

      - name: Install starknet-foundry via asdf
        uses: asdf-vm/actions/install@v3
        with:
          tool_versions: starknet-foundry nightly-2026-02-20

      - name: Run tests
        run: scarb test -w
