name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.17.0-rc.4"

      - uses: software-mansion/setup-universal-sierra-compiler@v1
        with:
          universal-sierra-compiler-version: "v2.8.0-rc.0"

      - name: Install starknet-foundry via asdf
        uses: asdf-vm/actions/install@v3
        with:
          tool_versions: starknet-foundry nightly-2026-02-20

      - name: Run tests
        run: scarb test -w
        env:
          SCARB_IGNORE_CAIRO_VERSION: "true"
